INSERT INTO Service (ServiceId, ServiceCompanyName, ServiceName, ServiceDetails)
VALUES
    (1, 'ABC Service Company', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (2, 'ABC Service Company', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (3, 'QuickOil', 'Oil Change', 'Fast and efficient oil change service'),
    (4, 'QuickOil', 'Transmission Check', 'Fast and efficient oil change service'),
    (5, 'Sparkle Wash', 'Car Wash', 'Detailed inspection of brake system'),
    (6, 'XYZ Repairs', 'Transmission Check', 'Professional coolant system flushing'),
    (7, 'Brake Master', 'Express Oil Change', 'Fast and efficient oil change service'),
    (8, 'Electro Tune', 'Express Oil Change', 'Exterior and interior cleaning services'),
    (9, 'Coolant Experts', 'Brake Replacement', 'Quick oil change with minimal waiting time'),
    (10, 'QuickOil', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (11, 'Sparkle Wash', 'Regular Maintenance', 'Exterior and interior cleaning services'),
    (12, 'Brake Master', 'Car Wash', 'Quick oil change with minimal waiting time'),
    (13, 'Coolant Experts', 'Car Wash', 'Thorough inspection of transmission components'),
    (14, 'Speedy Repairs', 'Electrical System Check', 'Detailed inspection of brake system'),
    (15, 'Electro Tune', 'Brake Replacement', 'Thorough inspection of transmission components'),
    (16, 'Electro Tune', 'Coolant Flush', 'Detailed inspection of brake system'),
    (17, 'QuickOil', 'Brake Replacement', 'Check and repair electrical components'),
    (18, 'QuickOil', 'Electrical System Check', 'Detailed inspection of brake system'),
    (19, 'Speedy Repairs', 'Car Wash', 'Replacement of worn-out brake components'),
    (20, 'QuickOil', 'Express Oil Change', 'Check and repair electrical components'),
    (21, 'Electro Tune', 'Electrical System Check', 'Replacement of worn-out brake components'),
    (22, 'Express Oil Change', 'Car Wash', 'Check and repair electrical components'),
    (23, 'ABC Service Company', 'Transmission Check', 'Detailed inspection of brake system'),
    (24, 'Electro Tune', 'Express Oil Change', 'Exterior and interior cleaning services'),
    (25, 'Sparkle Wash', 'Coolant Flush', 'Professional coolant system flushing'),
    (26, 'Sunshine Detailing', 'Interior Detailing', 'Thorough inspection of transmission components'),
    (27, 'QuickOil', 'Interior Detailing', 'Scheduled maintenance and inspection'),
    (28, 'Coolant Experts', 'Oil Change', 'Deep cleaning of the vehicle interior'),
    (29, 'XYZ Repairs', 'Transmission Check', 'Professional coolant system flushing'),
    (30, 'Sunshine Detailing', 'Express Oil Change', 'Detailed inspection of brake system'),
    (31, 'Sparkle Wash', 'Interior Detailing', 'Fast and efficient oil change service'),
    (32, 'Coolant Experts', 'Brake Inspection', 'Check and repair electrical components'),
    (33, 'Sunshine Detailing', 'Express Oil Change', 'Replacement of worn-out brake components'),
    (34, 'QuickOil', 'Car Wash', 'Exterior and interior cleaning services'),
    (35, 'Brake Master', 'Express Oil Change', 'Detailed inspection of brake system'),
    (36, 'ABC Service Company', 'Interior Detailing', 'Replacement of worn-out brake components'),
    (37, 'Express Oil Change', 'Brake Inspection', 'Scheduled maintenance and inspection'),
    (38, 'Speedy Repairs', 'Brake Inspection', 'Scheduled maintenance and inspection'),
    (39, 'Express Oil Change', 'Brake Replacement', 'Thorough inspection of transmission components'),
    (40, 'Brake Master', 'Brake Replacement', 'Professional coolant system flushing'),
    (41, 'Speedy Repairs', 'Regular Maintenance', 'Exterior and interior cleaning services'),
    (42, 'Speedy Repairs', 'Car Wash', 'Detailed inspection of brake system'),
    (43, 'XYZ Repairs', 'Interior Detailing', 'Thorough inspection of transmission components'),
    (44, 'Brake Master', 'Transmission Check', 'Thorough inspection of transmission components'),
    (45, 'Sunshine Detailing', 'Brake Inspection', 'Detailed inspection of brake system'),
    (46, 'Sparkle Wash', 'Brake Replacement', 'Fast and efficient oil change service'),
    (47, 'ABC Service Company', 'Transmission Check', 'Deep cleaning of the vehicle interior'),
    (48, 'Speedy Repairs', 'Car Wash', 'Exterior and interior cleaning services'),
    (49, 'Sparkle Wash', 'Express Oil Change', 'Replacement of worn-out brake components'),
    (50, 'XYZ Repairs', 'Express Oil Change', 'Quick oil change with minimal waiting time'),
    (51, 'Electro Tune', 'Electrical System Check', 'Quick oil change with minimal waiting time'),
    (52, 'QuickOil', 'Regular Maintenance', 'Quick oil change with minimal waiting time'),
    (53, 'ABC Service Company', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (54, 'QuickOil', 'Express Oil Change', 'Check and repair electrical components'),
    (55, 'Coolant Experts', 'Brake Replacement', 'Replacement of worn-out brake components'),
    (56, 'Speedy Repairs', 'Interior Detailing', 'Detailed inspection of brake system'),
    (57, 'QuickOil', 'Regular Maintenance', 'Check and repair electrical components'),
    (58, 'XYZ Repairs', 'Express Oil Change', 'Exterior and interior cleaning services'),
    (59, 'Speedy Repairs', 'Oil Change', 'Thorough inspection of transmission components'),
    (60, 'Coolant Experts', 'Electrical System Check', 'Professional coolant system flushing'),
    (61, 'Speedy Repairs', 'Car Wash', 'Fast and efficient oil change service'),
    (62, 'Speedy Repairs', 'Regular Maintenance', 'Scheduled maintenance and inspection'),
    (63, 'ABC Service Company', 'Oil Change', 'Professional coolant system flushing'),
    (64, 'Brake Master', 'Brake Inspection', 'Thorough inspection of transmission components'),
    (65, 'XYZ Repairs', 'Interior Detailing', 'Professional coolant system flushing'),
    (66, 'Coolant Experts', 'Interior Detailing', 'Professional coolant system flushing'),
    (67, 'Coolant Experts', 'Regular Maintenance', 'Exterior and interior cleaning services'),
    (68, 'Brake Master', 'Car Wash', 'Fast and efficient oil change service'),
    (69, 'Electro Tune', 'Electrical System Check', 'Scheduled maintenance and inspection'),
    (70, 'XYZ Repairs', 'Interior Detailing', 'Deep cleaning of the vehicle interior'),
    (71, 'Speedy Repairs', 'Brake Replacement', 'Detailed inspection of brake system'),
    (72, 'Express Oil Change', 'Interior Detailing', 'Scheduled maintenance and inspection'),
    (73, 'XYZ Repairs', 'Oil Change', 'Check and repair electrical components'),
    (74, 'Sparkle Wash', 'Express Oil Change', 'Thorough inspection of transmission components'),
    (75, 'Sunshine Detailing', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (76, 'Express Oil Change', 'Electrical System Check', 'Exterior and interior cleaning services'),
    (77, 'ABC Service Company', 'Electrical System Check', 'Thorough inspection of transmission components'),
    (78, 'ABC Service Company', 'Oil Change', 'Quick oil change with minimal waiting time'),
    (79, 'Sunshine Detailing', 'Oil Change', 'Fast and efficient oil change service'),
    (80, 'Speedy Repairs', 'Express Oil Change', 'Quick oil change with minimal waiting time'),
    (81, 'Sunshine Detailing', 'Electrical System Check', 'Exterior and interior cleaning services'),
    (82, 'Brake Master', 'Transmission Check', 'Detailed inspection of brake system'),
    (83, 'Speedy Repairs', 'Car Wash', 'Quick oil change with minimal waiting time'),
    (84, 'Express Oil Change', 'Electrical System Check', 'Detailed inspection of brake system'),
    (85, 'ABC Service Company', 'Regular Maintenance', 'Replacement of worn-out brake components'),
    (86, 'QuickOil', 'Coolant Flush', 'Thorough inspection of transmission components'),
    (87, 'Express Oil Change', 'Car Wash', 'Check and repair electrical components'),
    (88, 'Sparkle Wash', 'Transmission Check', 'Scheduled maintenance and inspection'),
    (89, 'QuickOil', 'Express Oil Change', 'Exterior and interior cleaning services'),
    (90, 'Sparkle Wash', 'Transmission Check', 'Detailed inspection of brake system'),
    (91, 'Sunshine Detailing', 'Brake Replacement', 'Replacement of worn-out brake components'),
    (92, 'Brake Master', 'Coolant Flush', 'Fast and efficient oil change service'),
    (93, 'XYZ Repairs', 'Car Wash', 'Detailed inspection of brake system'),
    (94, 'Sparkle Wash', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (95, 'Sparkle Wash', 'Car Wash', 'Deep cleaning of the vehicle interior'),
    (96, 'ABC Service Company', 'Express Oil Change', 'Thorough inspection of transmission components'),
    (97, 'ABC Service Company', 'Transmission Check', 'Thorough inspection of transmission components'),
    (98, 'Brake Master', 'Coolant Flush', 'Exterior and interior cleaning services'),
    (99, 'Brake Master', 'Car Wash', 'Fast and efficient oil change service'),
    (100, 'Sparkle Wash', 'Coolant Flush', 'Detailed inspection of brake system');