INSERT INTO Customer (CustomerId, UserID, EncryptedPaymentInfo)
VALUES
    (1, 86,CONVERT(varbinary(MAX), 'Credit Card - XXXX-XXXX-XXXX-XXXX')),
    (2, 20,CONVERT(varbinary(MAX), 'PayPal - user@example.com')),
    (3, 54,CONVERT(varbinary(MAX), 'Debit Card - YYYY-YYYY-YYYY-YYYY')),
    (4, 33,CONVERT(varbinary(MAX), 'Bank Transfer - Account: XXXXXXXX')),
    (5, 86,CONVERT(varbinary(MAX), 'Routing: YYYYYYYY')),
    (6, 14,CONVERT(varbinary(MAX), 'Cash on Delivery')),
    (7, 1,CONVERT(varbinary(MAX), 'Credit Card - ZZZZ-ZZZZ-ZZZZ-ZZZZ')),
    (8, 14,CONVERT(varbinary(MAX), 'Debit Card - KKKK-KKKK-KKKK-KKKK')),
    (9, 3,CONVERT(varbinary(MAX), 'PayPal - user2@example.com')),
    (10, 65,CONVERT(varbinary(MAX), 'Bank Transfer - Account: QQQQ-QQQQ-QQQQ')),
    (11, 75,CONVERT(varbinary(MAX), 'Routing: WWWW-WWWW-WWWW')),
    (12, 16,CONVERT(varbinary(MAX), 'Cash on Delivery')),
    (13, 50,CONVERT(varbinary(MAX), 'Credit Card - XXXX-XXXX-XXXX-XXXX')),
    (14, 30,CONVERT(varbinary(MAX), 'PayPal - user@example.com')),
    (15, 79,CONVERT(varbinary(MAX), 'Debit Card - YYYY-YYYY-YYYY-YYYY')),
    (16, 90,CONVERT(varbinary(MAX), 'Bank Transfer - Account: XXXXXXXX')),
    (17, 47,CONVERT(varbinary(MAX), 'Routing: YYYYYYYY')),
    (18, 10,CONVERT(varbinary(MAX), 'Cash on Delivery')),
    (19, 90,CONVERT(varbinary(MAX), 'Credit Card - ZZZZ-ZZZZ-ZZZZ-ZZZZ')),
    (20, 16,CONVERT(varbinary(MAX), 'Debit Card - KKKK-KKKK-KKKK-KKKK')),
    (21, 1,CONVERT(varbinary(MAX), 'PayPal - user2@example.com')),
    (22, 78,CONVERT(varbinary(MAX), 'Bank Transfer - Account: QQQQ-QQQQ-QQQQ')),
    (23, 26,CONVERT(varbinary(MAX), 'Routing: WWWW-WWWW-WWWW')),
    (24, 19,CONVERT(varbinary(MAX), 'Cash on Delivery')),
    (25, 5,CONVERT(varbinary(MAX), 'Credit Card - XXXX-XXXX-XXXX-XXXX')),
    (26, 89,CONVERT(varbinary(MAX), 'PayPal - user@example.com')),
    (27, 13,CONVERT(varbinary(MAX), 'Debit Card - YYYY-YYYY-YYYY-YYYY')),
    (28, 35,CONVERT(varbinary(MAX), 'Bank Transfer - Account: XXXXXXXX')),
    (29, 4,CONVERT(varbinary(MAX), 'Routing: YYYYYYYY')),
    (30, 84,CONVERT(varbinary(MAX), 'Cash on Delivery')),
    (31, 65,CONVERT(varbinary(MAX), 'Credit Card - ZZZZ-ZZZZ-ZZZZ-ZZZZ')),
    (32, 84,CONVERT(varbinary(MAX), 'Debit Card - KKKK-KKKK-KKKK-KKKK')),
    (33, 6,CONVERT(varbinary(MAX), 'PayPal - user2@example.com')),
    (34, 33,CONVERT(varbinary(MAX), 'Bank Transfer - Account: QQQQ-QQQQ-QQQQ')),
    (35, 76,CONVERT(varbinary(MAX), 'Routing: WWWW-WWWW-WWWW')),
    (36, 48,CONVERT(varbinary(MAX), 'Cash on Delivery')),
    (37, 66,CONVERT(varbinary(MAX), 'Credit Card - XXXX-XXXX-XXXX-XXXX')),
    (38, 68,CONVERT(varbinary(MAX), 'PayPal - user@example.com')),
    (39, 36,CONVERT(varbinary(MAX), 'Debit Card - YYYY-YYYY-YYYY-YYYY')),
    (40, 61,CONVERT(varbinary(MAX), 'Bank Transfer - Account: XXXXXXXX')),
    (41, 95,CONVERT(varbinary(MAX), 'Routing: YYYYYYYY')),
    (42, 9,CONVERT(varbinary(MAX), 'Cash on Delivery')),
    (43, 68,CONVERT(varbinary(MAX), 'Credit Card - ZZZZ-ZZZZ-ZZZZ-ZZZZ')),
    (44, 2,CONVERT(varbinary(MAX), 'Debit Card - KKKK-KKKK-KKKK-KKKK')),
    (45, 55,CONVERT(varbinary(MAX), 'PayPal - user2@example.com')),
    (46, 2,CONVERT(varbinary(MAX), 'Bank Transfer - Account: QQQQ-QQQQ-QQQQ')),
    (47, 49,CONVERT(varbinary(MAX), 'Routing: WWWW-WWWW-WWWW')),
    (48, 97,CONVERT(varbinary(MAX), 'Cash on Delivery')),
    (49, 63,CONVERT(varbinary(MAX), 'Credit Card - XXXX-XXXX-XXXX-XXXX')),
    (50, 15,CONVERT(varbinary(MAX), 'PayPal - user@example.com')),
    (51, 87,CONVERT(varbinary(MAX), 'Debit Card - YYYY-YYYY-YYYY-YYYY')),
    (52, 33,CONVERT(varbinary(MAX), 'Bank Transfer - Account: XXXXXXXX')),
    (53, 20,CONVERT(varbinary(MAX), 'Routing: YYYYYYYY')),
    (54, 4,CONVERT(varbinary(MAX), 'Cash on Delivery')),
    (55, 52,CONVERT(varbinary(MAX), 'Credit Card - ZZZZ-ZZZZ-ZZZZ-ZZZZ')),
    (56, 59,CONVERT(varbinary(MAX), 'Debit Card - KKKK-KKKK-KKKK-KKKK')),
    (57, 34,CONVERT(varbinary(MAX), 'PayPal - user2@example.com')),
    (58, 26,CONVERT(varbinary(MAX), 'Bank Transfer - Account: QQQQ-QQQQ-QQQQ')),
    (59, 35,CONVERT(varbinary(MAX), 'Routing: WWWW-WWWW-WWWW')),
    (60, 59,CONVERT(varbinary(MAX), 'Cash on Delivery'));