INSERT INTO Customer (CustomerId, UserID, EncryptedPaymentInfo)
VALUES
    (1, 9,CONVERT(varbinary(MAX),'Credit Card - XXXX-XXXX-XXXX-XXXX')),
    (2, 6,CONVERT(varbinary(MAX),'PayPal - user@example.com')),
    (3, 54,CONVERT(varbinary(MAX),'Debit Card - YYYY-YYYY-YYYY-YYYY')),
    (4, 50,CONVERT(varbinary(MAX),'Bank Transfer - Account: XXXXXXXX')),
    (5, 26,CONVERT(varbinary(MAX),'Routing: YYYYYYYY')),
    (6, 24,CONVERT(varbinary(MAX),'Cash on Delivery')),
    (7, 11,CONVERT(varbinary(MAX),'Credit Card - ZZZZ-ZZZZ-ZZZZ-ZZZZ')),
    (8, 33,CONVERT(varbinary(MAX),'Debit Card - KKKK-KKKK-KKKK-KKKK')),
    (9, 31,CONVERT(varbinary(MAX),'PayPal - user2@example.com')),
    (10, 26,CONVERT(varbinary(MAX),'Bank Transfer - Account: QQQQ-QQQQ-QQQQ')),
    (11, 16,CONVERT(varbinary(MAX),'Routing: WWWW-WWWW-WWWW')),
    (12, 59,CONVERT(varbinary(MAX),'Cash on Delivery')),
    (13, 14,CONVERT(varbinary(MAX),'Credit Card - XXXX-XXXX-XXXX-XXXX')),
    (14, 31,CONVERT(varbinary(MAX),'PayPal - user@example.com')),
    (15, 47,CONVERT(varbinary(MAX),'Debit Card - YYYY-YYYY-YYYY-YYYY')),
    (16, 54,CONVERT(varbinary(MAX),'Bank Transfer - Account: XXXXXXXX')),
    (17, 13,CONVERT(varbinary(MAX),'Routing: YYYYYYYY')),
    (18, 9,CONVERT(varbinary(MAX),'Cash on Delivery')),
    (19, 53,CONVERT(varbinary(MAX),'Credit Card - ZZZZ-ZZZZ-ZZZZ-ZZZZ')),
    (20, 7,CONVERT(varbinary(MAX),'Debit Card - KKKK-KKKK-KKKK-KKKK')),
    (21, 3,CONVERT(varbinary(MAX),'PayPal - user2@example.com')),
    (22, 41,CONVERT(varbinary(MAX),'Bank Transfer - Account: QQQQ-QQQQ-QQQQ')),
    (23, 9,CONVERT(varbinary(MAX),'Routing: WWWW-WWWW-WWWW')),
    (24, 55,CONVERT(varbinary(MAX),'Cash on Delivery')),
    (25, 29,CONVERT(varbinary(MAX),'Credit Card - XXXX-XXXX-XXXX-XXXX')),
    (26, 42,CONVERT(varbinary(MAX),'PayPal - user@example.com')),
    (27, 33,CONVERT(varbinary(MAX),'Debit Card - YYYY-YYYY-YYYY-YYYY')),
    (28, 1,CONVERT(varbinary(MAX),'Bank Transfer - Account: XXXXXXXX')),
    (29, 42,CONVERT(varbinary(MAX),'Routing: YYYYYYYY')),
    (30, 6,CONVERT(varbinary(MAX),'Cash on Delivery')),
    (31, 14,CONVERT(varbinary(MAX),'Credit Card - ZZZZ-ZZZZ-ZZZZ-ZZZZ')),
    (32, 19,CONVERT(varbinary(MAX),'Debit Card - KKKK-KKKK-KKKK-KKKK')),
    (33, 15,CONVERT(varbinary(MAX),'PayPal - user2@example.com')),
    (34, 11,CONVERT(varbinary(MAX),'Bank Transfer - Account: QQQQ-QQQQ-QQQQ')),
    (35, 16,CONVERT(varbinary(MAX),'Routing: WWWW-WWWW-WWWW')),
    (36, 20,CONVERT(varbinary(MAX),'Cash on Delivery')),
    (37, 14,CONVERT(varbinary(MAX),'Credit Card - XXXX-XXXX-XXXX-XXXX')),
    (38, 33,CONVERT(varbinary(MAX),'PayPal - user@example.com')),
    (39, 1,CONVERT(varbinary(MAX),'Debit Card - YYYY-YYYY-YYYY-YYYY')),
    (40, 4,CONVERT(varbinary(MAX),'Bank Transfer - Account: XXXXXXXX')),
    (41, 13,CONVERT(varbinary(MAX),'Routing: YYYYYYYY')),
    (42, 20,CONVERT(varbinary(MAX),'Cash on Delivery')),
    (43, 1,CONVERT(varbinary(MAX),'Credit Card - ZZZZ-ZZZZ-ZZZZ-ZZZZ')),
    (44, 56,CONVERT(varbinary(MAX),'Debit Card - KKKK-KKKK-KKKK-KKKK')),
    (45, 55,CONVERT(varbinary(MAX),'PayPal - user2@example.com')),
    (46, 35,CONVERT(varbinary(MAX),'Bank Transfer - Account: QQQQ-QQQQ-QQQQ')),
    (47, 6,CONVERT(varbinary(MAX),'Routing: WWWW-WWWW-WWWW')),
    (48, 60,CONVERT(varbinary(MAX),'Cash on Delivery')),
    (49, 25,CONVERT(varbinary(MAX),'Credit Card - XXXX-XXXX-XXXX-XXXX')),
    (50, 23,CONVERT(varbinary(MAX),'PayPal - user@example.com')),
    (51, 59,CONVERT(varbinary(MAX),'Debit Card - YYYY-YYYY-YYYY-YYYY')),
    (52, 29,CONVERT(varbinary(MAX),'Bank Transfer - Account: XXXXXXXX')),
    (53, 54,CONVERT(varbinary(MAX),'Routing: YYYYYYYY')),
    (54, 55,CONVERT(varbinary(MAX),'Cash on Delivery')),
    (55, 13,CONVERT(varbinary(MAX),'Credit Card - ZZZZ-ZZZZ-ZZZZ-ZZZZ')),
    (56, 43,CONVERT(varbinary(MAX),'Debit Card - KKKK-KKKK-KKKK-KKKK')),
    (57, 3,CONVERT(varbinary(MAX),'PayPal - user2@example.com')),
    (58, 55,CONVERT(varbinary(MAX),'Bank Transfer - Account: QQQQ-QQQQ-QQQQ')),
    (59, 47,CONVERT(varbinary(MAX),'Routing: WWWW-WWWW-WWWW')),
    (60, 25,CONVERT(varbinary(MAX),'Cash on Delivery'));