insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (1, 'ABC Service Company', 'Regular Maintenance', 'Detailed inspection of brake system');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (2, 'ABC Service Company', 'Coolant Flush', 'Deep cleaning of the vehicle interior');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (3, 'QuickOil', 'Oil Change', 'Fast and efficient oil change service');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (4, 'QuickOil', 'Transmission Check', 'Fast and efficient oil change service');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (5, 'Sparkle Wash', 'Car Wash', 'Detailed inspection of brake system');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (6, 'XYZ Repairs', 'Transmission Check', 'Professional coolant system flushing');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (7, 'Brake Master', 'Express Oil Change', 'Fast and efficient oil change service');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (8, 'Electro Tune', 'Express Oil Change', 'Exterior and interior cleaning services');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (9, 'Coolant Experts', 'Brake Replacement', 'Quick oil change with minimal waiting time');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (10, 'QuickOil', 'Coolant Flush', 'Deep cleaning of the vehicle interior');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (11, 'Sparkle Wash', 'Regular Maintenance', 'Exterior and interior cleaning services');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (12, 'Brake Master', 'Car Wash', 'Quick oil change with minimal waiting time');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (13, 'Coolant Experts', 'Car Wash', 'Thorough inspection of transmission components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (14, 'Speedy Repairs', 'Electrical System Check', 'Detailed inspection of brake system');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (15, 'Electro Tune', 'Brake Replacement', 'Thorough inspection of transmission components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (16, 'Electro Tune', 'Coolant Flush', 'Detailed inspection of brake system');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (17, 'QuickOil', 'Brake Replacement', 'Check and repair electrical components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (18, 'QuickOil', 'Electrical System Check', 'Detailed inspection of brake system');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (19, 'Speedy Repairs', 'Car Wash', 'Replacement of worn-out brake components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (20, 'QuickOil', 'Express Oil Change', 'Check and repair electrical components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (21, 'Electro Tune', 'Electrical System Check', 'Replacement of worn-out brake components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (22, 'Express Oil Change', 'Car Wash', 'Check and repair electrical components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (23, 'ABC Service Company', 'Transmission Check', 'Detailed inspection of brake system');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (24, 'Electro Tune', 'Express Oil Change', 'Exterior and interior cleaning services');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (25, 'Sparkle Wash', 'Coolant Flush', 'Professional coolant system flushing');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (26, 'Sunshine Detailing', 'Interior Detailing', 'Thorough inspection of transmission components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (27, 'QuickOil', 'Interior Detailing', 'Scheduled maintenance and inspection');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (28, 'Coolant Experts', 'Oil Change', 'Deep cleaning of the vehicle interior');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (29, 'XYZ Repairs', 'Transmission Check', 'Professional coolant system flushing');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (30, 'Sunshine Detailing', 'Express Oil Change', 'Detailed inspection of brake system');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (31, 'Sparkle Wash', 'Interior Detailing', 'Fast and efficient oil change service');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (32, 'Coolant Experts', 'Brake Inspection', 'Check and repair electrical components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (33, 'Sunshine Detailing', 'Express Oil Change', 'Replacement of worn-out brake components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (34, 'QuickOil', 'Car Wash', 'Exterior and interior cleaning services');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (35, 'Brake Master', 'Express Oil Change', 'Detailed inspection of brake system');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (36, 'ABC Service Company', 'Interior Detailing', 'Replacement of worn-out brake components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (37, 'Express Oil Change', 'Brake Inspection', 'Scheduled maintenance and inspection');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (38, 'Speedy Repairs', 'Brake Inspection', 'Scheduled maintenance and inspection');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (39, 'Express Oil Change', 'Brake Replacement', 'Thorough inspection of transmission components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (40, 'Brake Master', 'Brake Replacement', 'Professional coolant system flushing');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (41, 'Speedy Repairs', 'Regular Maintenance', 'Exterior and interior cleaning services');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (42, 'Speedy Repairs', 'Car Wash', 'Detailed inspection of brake system');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (43, 'XYZ Repairs', 'Interior Detailing', 'Thorough inspection of transmission components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (44, 'Brake Master', 'Transmission Check', 'Thorough inspection of transmission components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (45, 'Sunshine Detailing', 'Brake Inspection', 'Detailed inspection of brake system');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (46, 'Sparkle Wash', 'Brake Replacement', 'Fast and efficient oil change service');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (47, 'ABC Service Company', 'Transmission Check', 'Deep cleaning of the vehicle interior');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (48, 'Speedy Repairs', 'Car Wash', 'Exterior and interior cleaning services');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (49, 'Sparkle Wash', 'Express Oil Change', 'Replacement of worn-out brake components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (50, 'XYZ Repairs', 'Express Oil Change', 'Quick oil change with minimal waiting time');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (51, 'Electro Tune', 'Electrical System Check', 'Quick oil change with minimal waiting time');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (52, 'QuickOil', 'Regular Maintenance', 'Quick oil change with minimal waiting time');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (53, 'ABC Service Company', 'Coolant Flush', 'Deep cleaning of the vehicle interior');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (54, 'QuickOil', 'Express Oil Change', 'Check and repair electrical components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (55, 'Coolant Experts', 'Brake Replacement', 'Replacement of worn-out brake components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (56, 'Speedy Repairs', 'Interior Detailing', 'Detailed inspection of brake system');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (57, 'QuickOil', 'Regular Maintenance', 'Check and repair electrical components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (58, 'XYZ Repairs', 'Express Oil Change', 'Exterior and interior cleaning services');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (59, 'Speedy Repairs', 'Oil Change', 'Thorough inspection of transmission components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (60, 'Coolant Experts', 'Electrical System Check', 'Professional coolant system flushing');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (61, 'Speedy Repairs', 'Car Wash', 'Fast and efficient oil change service');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (62, 'Speedy Repairs', 'Regular Maintenance', 'Scheduled maintenance and inspection');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (63, 'ABC Service Company', 'Oil Change', 'Professional coolant system flushing');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (64, 'Brake Master', 'Brake Inspection', 'Thorough inspection of transmission components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (65, 'XYZ Repairs', 'Interior Detailing', 'Professional coolant system flushing');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (66, 'Coolant Experts', 'Interior Detailing', 'Professional coolant system flushing');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (67, 'Coolant Experts', 'Regular Maintenance', 'Exterior and interior cleaning services');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (68, 'Brake Master', 'Car Wash', 'Fast and efficient oil change service');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (69, 'Electro Tune', 'Electrical System Check', 'Scheduled maintenance and inspection');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (70, 'XYZ Repairs', 'Interior Detailing', 'Deep cleaning of the vehicle interior');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (71, 'Speedy Repairs', 'Brake Replacement', 'Detailed inspection of brake system');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (72, 'Express Oil Change', 'Interior Detailing', 'Scheduled maintenance and inspection');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (73, 'XYZ Repairs', 'Oil Change', 'Check and repair electrical components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (74, 'Sparkle Wash', 'Express Oil Change', 'Thorough inspection of transmission components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (75, 'Sunshine Detailing', 'Coolant Flush', 'Deep cleaning of the vehicle interior');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (76, 'Express Oil Change', 'Electrical System Check', 'Exterior and interior cleaning services');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (77, 'ABC Service Company', 'Electrical System Check', 'Thorough inspection of transmission components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (78, 'ABC Service Company', 'Oil Change', 'Quick oil change with minimal waiting time');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (79, 'Sunshine Detailing', 'Oil Change', 'Fast and efficient oil change service');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (80, 'Speedy Repairs', 'Express Oil Change', 'Quick oil change with minimal waiting time');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (81, 'Sunshine Detailing', 'Electrical System Check', 'Exterior and interior cleaning services');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (82, 'Brake Master', 'Transmission Check', 'Detailed inspection of brake system');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (83, 'Speedy Repairs', 'Car Wash', 'Quick oil change with minimal waiting time');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (84, 'Express Oil Change', 'Electrical System Check', 'Detailed inspection of brake system');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (85, 'ABC Service Company', 'Regular Maintenance', 'Replacement of worn-out brake components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (86, 'QuickOil', 'Coolant Flush', 'Thorough inspection of transmission components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (87, 'Express Oil Change', 'Car Wash', 'Check and repair electrical components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (88, 'Sparkle Wash', 'Transmission Check', 'Scheduled maintenance and inspection');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (89, 'QuickOil', 'Express Oil Change', 'Exterior and interior cleaning services');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (90, 'Sparkle Wash', 'Transmission Check', 'Detailed inspection of brake system');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (91, 'Sunshine Detailing', 'Brake Replacement', 'Replacement of worn-out brake components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (92, 'Brake Master', 'Coolant Flush', 'Fast and efficient oil change service');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (93, 'XYZ Repairs', 'Car Wash', 'Detailed inspection of brake system');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (94, 'Sparkle Wash', 'Coolant Flush', 'Deep cleaning of the vehicle interior');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (95, 'Sparkle Wash', 'Car Wash', 'Deep cleaning of the vehicle interior');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (96, 'ABC Service Company', 'Express Oil Change', 'Thorough inspection of transmission components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (97, 'ABC Service Company', 'Transmission Check', 'Thorough inspection of transmission components');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (98, 'Brake Master', 'Coolant Flush', 'Exterior and interior cleaning services');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (99, 'Brake Master', 'Car Wash', 'Fast and efficient oil change service');
insert into Service_MOCK_DATA (serviceid, servicecompanyname, servicename, servicedetails) values (100, 'Sparkle Wash', 'Coolant Flush', 'Detailed inspection of brake system');
