INSERT INTO Service (ServiceId, ServiceCompanyName, ServiceName, ServiceDetails)
VALUES
    (1, 'Express Oil Change', 'Express Oil Change', 'Scheduled maintenance and inspection'),
    (2, 'Coolant Experts', 'Interior Detailing', 'Quick oil change with minimal waiting time'),
    (3, 'Sunshine Detailing', 'Oil Change', 'Thorough inspection of transmission components'),
    (4, 'Brake Master', 'Express Oil Change', 'Replacement of worn-out brake components'),
    (5, 'Electro Tune', 'Coolant Flush', 'Exterior and interior cleaning services'),
    (6, 'Speedy Repairs', 'Coolant Flush', 'Thorough inspection of transmission components'),
    (7, 'QuickOil', 'Oil Change', 'Thorough inspection of transmission components'),
    (8, 'Express Oil Change', 'Oil Change', 'Scheduled maintenance and inspection'),
    (9, 'XYZ Repairs', 'Electrical System Check', 'Replacement of worn-out brake components'),
    (10, 'Brake Master', 'Brake Replacement', 'Scheduled maintenance and inspection'),
    (11, 'XYZ Repairs', 'Oil Change', 'Scheduled maintenance and inspection'),
    (12, 'ABC Service Company', 'Car Wash', 'Exterior and interior cleaning services'),
    (13, 'XYZ Repairs', 'Express Oil Change', 'Quick oil change with minimal waiting time'),
    (14, 'Speedy Repairs', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (15, 'Electro Tune', 'Interior Detailing', 'Fast and efficient oil change service'),
    (16, 'Electro Tune', 'Regular Maintenance', 'Scheduled maintenance and inspection'),
    (17, 'Express Oil Change', 'Electrical System Check', 'Scheduled maintenance and inspection'),
    (18, 'Coolant Experts', 'Transmission Check', 'Check and repair electrical components'),
    (19, 'Brake Master', 'Brake Replacement', 'Deep cleaning of the vehicle interior'),
    (20, 'Electro Tune', 'Regular Maintenance', 'Professional coolant system flushing'),
    (21, 'Brake Master', 'Car Wash', 'Fast and efficient oil change service'),
    (22, 'Sunshine Detailing', 'Brake Replacement', 'Fast and efficient oil change service'),
    (23, 'QuickOil', 'Car Wash', 'Scheduled maintenance and inspection'),
    (24, 'XYZ Repairs', 'Regular Maintenance', 'Check and repair electrical components'),
    (25, 'Speedy Repairs', 'Coolant Flush', 'Replacement of worn-out brake components'),
    (26, 'Sunshine Detailing', 'Car Wash', 'Professional coolant system flushing'),
    (27, 'Coolant Experts', 'Oil Change', 'Detailed inspection of brake system'),
    (28, 'Speedy Repairs', 'Transmission Check', 'Check and repair electrical components'),
    (29, 'Brake Master', 'Transmission Check', 'Scheduled maintenance and inspection'),
    (30, 'Speedy Repairs', 'Electrical System Check', 'Scheduled maintenance and inspection'),
    (31, 'Express Oil Change', 'Coolant Flush', 'Fast and efficient oil change service'),
    (32, 'Speedy Repairs', 'Car Wash', 'Check and repair electrical components'),
    (33, 'ABC Service Company', 'Regular Maintenance', 'Replacement of worn-out brake components'),
    (34, 'Electro Tune', 'Car Wash', 'Replacement of worn-out brake components'),
    (35, 'Brake Master', 'Brake Inspection', 'Deep cleaning of the vehicle interior'),
    (36, 'QuickOil', 'Regular Maintenance', 'Thorough inspection of transmission components'),
    (37, 'ABC Service Company', 'Car Wash', 'Fast and efficient oil change service'),
    (38, 'Sunshine Detailing', 'Interior Detailing', 'Replacement of worn-out brake components'),
    (39, 'Electro Tune', 'Brake Inspection', 'Replacement of worn-out brake components'),
    (40, 'ABC Service Company', 'Transmission Check', 'Detailed inspection of brake system'),
    (41, 'Brake Master', 'Oil Change', 'Replacement of worn-out brake components'),
    (42, 'Coolant Experts', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (43, 'Express Oil Change', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (44, 'ABC Service Company', 'Interior Detailing', 'Exterior and interior cleaning services'),
    (45, 'XYZ Repairs', 'Electrical System Check', 'Deep cleaning of the vehicle interior'),
    (46, 'Sunshine Detailing', 'Brake Inspection', 'Thorough inspection of transmission components'),
    (47, 'Sparkle Wash', 'Interior Detailing', 'Fast and efficient oil change service'),
    (48, 'Coolant Experts', 'Coolant Flush', 'Fast and efficient oil change service'),
    (49, 'QuickOil', 'Express Oil Change', 'Thorough inspection of transmission components'),
    (50, 'ABC Service Company', 'Transmission Check', 'Fast and efficient oil change service'),
    (51, 'Coolant Experts', 'Regular Maintenance', 'Fast and efficient oil change service'),
    (52, 'ABC Service Company', 'Car Wash', 'Exterior and interior cleaning services'),
    (53, 'Coolant Experts', 'Brake Inspection', 'Check and repair electrical components'),
    (54, 'Coolant Experts', 'Oil Change', 'Replacement of worn-out brake components'),
    (55, 'Sparkle Wash', 'Brake Inspection', 'Scheduled maintenance and inspection'),
    (56, 'Coolant Experts', 'Brake Inspection', 'Thorough inspection of transmission components'),
    (57, 'QuickOil', 'Express Oil Change', 'Replacement of worn-out brake components'),
    (58, 'Coolant Experts', 'Oil Change', 'Professional coolant system flushing'),
    (59, 'Electro Tune', 'Express Oil Change', 'Replacement of worn-out brake components'),
    (60, 'Sparkle Wash', 'Regular Maintenance', 'Quick oil change with minimal waiting time'),
    (61, 'Sunshine Detailing', 'Transmission Check', 'Replacement of worn-out brake components'),
    (62, 'Coolant Experts', 'Express Oil Change', 'Exterior and interior cleaning services'),
    (63, 'ABC Service Company', 'Express Oil Change', 'Detailed inspection of brake system'),
    (64, 'QuickOil', 'Coolant Flush', 'Fast and efficient oil change service'),
    (65, 'Sparkle Wash', 'Brake Replacement', 'Scheduled maintenance and inspection'),
    (66, 'Express Oil Change', 'Interior Detailing', 'Quick oil change with minimal waiting time'),
    (67, 'XYZ Repairs', 'Electrical System Check', 'Thorough inspection of transmission components'),
    (68, 'Electro Tune', 'Regular Maintenance', 'Quick oil change with minimal waiting time'),
    (69, 'XYZ Repairs', 'Brake Replacement', 'Fast and efficient oil change service'),
    (70, 'Express Oil Change', 'Regular Maintenance', 'Exterior and interior cleaning services'),
    (71, 'ABC Service Company', 'Brake Replacement', 'Quick oil change with minimal waiting time'),
    (72, 'ABC Service Company', 'Express Oil Change', 'Replacement of worn-out brake components'),
    (73, 'Brake Master', 'Brake Inspection', 'Professional coolant system flushing'),
    (74, 'XYZ Repairs', 'Coolant Flush', 'Scheduled maintenance and inspection'),
    (75, 'Coolant Experts', 'Oil Change', 'Detailed inspection of brake system'),
    (76, 'Electro Tune', 'Electrical System Check', 'Professional coolant system flushing'),
    (77, 'ABC Service Company', 'Brake Replacement', 'Scheduled maintenance and inspection'),
    (78, 'Coolant Experts', 'Brake Inspection', 'Professional coolant system flushing'),
    (79, 'QuickOil', 'Car Wash', 'Exterior and interior cleaning services'),
    (80, 'QuickOil', 'Electrical System Check', 'Exterior and interior cleaning services'),
    (81, 'ABC Service Company', 'Oil Change', 'Deep cleaning of the vehicle interior'),
    (82, 'Sunshine Detailing', 'Regular Maintenance', 'Professional coolant system flushing'),
    (83, 'Express Oil Change', 'Oil Change', 'Exterior and interior cleaning services'),
    (84, 'Speedy Repairs', 'Oil Change', 'Deep cleaning of the vehicle interior'),
    (85, 'XYZ Repairs', 'Transmission Check', 'Exterior and interior cleaning services'),
    (86, 'Sparkle Wash', 'Interior Detailing', 'Deep cleaning of the vehicle interior'),
    (87, 'QuickOil', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (88, 'QuickOil', 'Interior Detailing', 'Scheduled maintenance and inspection'),
    (89, 'QuickOil', 'Oil Change', 'Deep cleaning of the vehicle interior'),
    (90, 'Electro Tune', 'Interior Detailing', 'Fast and efficient oil change service'),
    (91, 'XYZ Repairs', 'Interior Detailing', 'Deep cleaning of the vehicle interior'),
    (92, 'Electro Tune', 'Interior Detailing', 'Thorough inspection of transmission components'),
    (93, 'Speedy Repairs', 'Interior Detailing', 'Replacement of worn-out brake components'),
    (94, 'Sunshine Detailing', 'Electrical System Check', 'Replacement of worn-out brake components'),
    (95, 'QuickOil', 'Interior Detailing', 'Thorough inspection of transmission components'),
    (96, 'XYZ Repairs', 'Express Oil Change', 'Deep cleaning of the vehicle interior'),
    (97, 'Express Oil Change', 'Express Oil Change', 'Detailed inspection of brake system'),
    (98, 'ABC Service Company', 'Brake Inspection', 'Detailed inspection of brake system'),
    (99, 'QuickOil', 'Regular Maintenance', 'Exterior and interior cleaning services'),
    (100, 'QuickOil', 'Brake Inspection', 'Scheduled maintenance and inspection'),
    (101, 'Brake Master', 'Interior Detailing', 'Detailed inspection of brake system'),
    (102, 'Express Oil Change', 'Electrical System Check', 'Exterior and interior cleaning services'),
    (103, 'XYZ Repairs', 'Interior Detailing', 'Quick oil change with minimal waiting time'),
    (104, 'XYZ Repairs', 'Regular Maintenance', 'Check and repair electrical components'),
    (105, 'ABC Service Company', 'Regular Maintenance', 'Thorough inspection of transmission components'),
    (106, 'Speedy Repairs', 'Interior Detailing', 'Replacement of worn-out brake components'),
    (107, 'ABC Service Company', 'Brake Inspection', 'Detailed inspection of brake system'),
    (108, 'Speedy Repairs', 'Car Wash', 'Deep cleaning of the vehicle interior'),
    (109, 'ABC Service Company', 'Oil Change', 'Replacement of worn-out brake components'),
    (110, 'Coolant Experts', 'Car Wash', 'Professional coolant system flushing'),
    (111, 'QuickOil', 'Express Oil Change', 'Deep cleaning of the vehicle interior'),
    (112, 'ABC Service Company', 'Coolant Flush', 'Check and repair electrical components'),
    (113, 'XYZ Repairs', 'Electrical System Check', 'Check and repair electrical components'),
    (114, 'Speedy Repairs', 'Car Wash', 'Check and repair electrical components'),
    (115, 'Electro Tune', 'Oil Change', 'Professional coolant system flushing'),
    (116, 'Express Oil Change', 'Regular Maintenance', 'Exterior and interior cleaning services'),
    (117, 'ABC Service Company', 'Brake Replacement', 'Check and repair electrical components'),
    (118, 'XYZ Repairs', 'Brake Replacement', 'Quick oil change with minimal waiting time'),
    (119, 'XYZ Repairs', 'Oil Change', 'Quick oil change with minimal waiting time'),
    (120, 'QuickOil', 'Coolant Flush', 'Check and repair electrical components'),
    (121, 'ABC Service Company', 'Transmission Check', 'Fast and efficient oil change service'),
    (122, 'Coolant Experts', 'Coolant Flush', 'Exterior and interior cleaning services'),
    (123, 'XYZ Repairs', 'Oil Change', 'Fast and efficient oil change service'),
    (124, 'Sparkle Wash', 'Transmission Check', 'Replacement of worn-out brake components'),
    (125, 'Brake Master', 'Regular Maintenance', 'Deep cleaning of the vehicle interior'),
    (126, 'Coolant Experts', 'Brake Inspection', 'Fast and efficient oil change service'),
    (127, 'Electro Tune', 'Oil Change', 'Deep cleaning of the vehicle interior'),
    (128, 'Express Oil Change', 'Brake Replacement', 'Quick oil change with minimal waiting time'),
    (129, 'Electro Tune', 'Brake Inspection', 'Deep cleaning of the vehicle interior'),
    (130, 'Express Oil Change', 'Brake Replacement', 'Exterior and interior cleaning services'),
    (131, 'Electro Tune', 'Regular Maintenance', 'Thorough inspection of transmission components'),
    (132, 'Brake Master', 'Transmission Check', 'Check and repair electrical components'),
    (133, 'Express Oil Change', 'Coolant Flush', 'Thorough inspection of transmission components'),
    (134, 'Sparkle Wash', 'Car Wash', 'Check and repair electrical components'),
    (135, 'Sparkle Wash', 'Brake Replacement', 'Fast and efficient oil change service'),
    (136, 'Express Oil Change', 'Coolant Flush', 'Scheduled maintenance and inspection'),
    (137, 'Brake Master', 'Electrical System Check', 'Quick oil change with minimal waiting time'),
    (138, 'Coolant Experts', 'Interior Detailing', 'Thorough inspection of transmission components'),
    (139, 'Brake Master', 'Transmission Check', 'Fast and efficient oil change service'),
    (140, 'ABC Service Company', 'Electrical System Check', 'Scheduled maintenance and inspection'),
    (141, 'Speedy Repairs', 'Electrical System Check', 'Check and repair electrical components'),
    (142, 'ABC Service Company', 'Brake Replacement', 'Quick oil change with minimal waiting time'),
    (143, 'ABC Service Company', 'Brake Replacement', 'Detailed inspection of brake system'),
    (144, 'Speedy Repairs', 'Express Oil Change', 'Replacement of worn-out brake components'),
    (145, 'Electro Tune', 'Brake Replacement', 'Detailed inspection of brake system'),
    (146, 'Coolant Experts', 'Regular Maintenance', 'Professional coolant system flushing'),
    (147, 'Coolant Experts', 'Brake Replacement', 'Exterior and interior cleaning services'),
    (148, 'Express Oil Change', 'Oil Change', 'Quick oil change with minimal waiting time'),
    (149, 'Speedy Repairs', 'Car Wash', 'Replacement of worn-out brake components'),
    (150, 'Sunshine Detailing', 'Interior Detailing', 'Quick oil change with minimal waiting time'),
    (151, 'Sparkle Wash', 'Transmission Check', 'Replacement of worn-out brake components'),
    (152, 'Sunshine Detailing', 'Car Wash', 'Scheduled maintenance and inspection'),
    (153, 'Speedy Repairs', 'Brake Replacement', 'Scheduled maintenance and inspection'),
    (154, 'Express Oil Change', 'Express Oil Change', 'Scheduled maintenance and inspection'),
    (155, 'Speedy Repairs', 'Car Wash', 'Quick oil change with minimal waiting time'),
    (156, 'Brake Master', 'Regular Maintenance', 'Thorough inspection of transmission components'),
    (157, 'Electro Tune', 'Brake Inspection', 'Fast and efficient oil change service'),
    (158, 'XYZ Repairs', 'Oil Change', 'Fast and efficient oil change service'),
    (159, 'Speedy Repairs', 'Interior Detailing', 'Fast and efficient oil change service'),
    (160, 'Express Oil Change', 'Brake Inspection', 'Deep cleaning of the vehicle interior'),
    (161, 'QuickOil', 'Brake Inspection', 'Detailed inspection of brake system'),
    (162, 'Coolant Experts', 'Brake Inspection', 'Thorough inspection of transmission components'),
    (163, 'Express Oil Change', 'Brake Inspection', 'Detailed inspection of brake system'),
    (164, 'Speedy Repairs', 'Express Oil Change', 'Thorough inspection of transmission components'),
    (165, 'XYZ Repairs', 'Interior Detailing', 'Quick oil change with minimal waiting time'),
    (166, 'Express Oil Change', 'Transmission Check', 'Thorough inspection of transmission components'),
    (167, 'ABC Service Company', 'Car Wash', 'Deep cleaning of the vehicle interior'),
    (168, 'Sunshine Detailing', 'Express Oil Change', 'Professional coolant system flushing'),
    (169, 'XYZ Repairs', 'Interior Detailing', 'Scheduled maintenance and inspection'),
    (170, 'QuickOil', 'Car Wash', 'Check and repair electrical components'),
    (171, 'QuickOil', 'Brake Replacement', 'Exterior and interior cleaning services'),
    (172, 'XYZ Repairs', 'Express Oil Change', 'Scheduled maintenance and inspection'),
    (173, 'Sparkle Wash', 'Transmission Check', 'Quick oil change with minimal waiting time'),
    (174, 'QuickOil', 'Transmission Check', 'Replacement of worn-out brake components'),
    (175, 'XYZ Repairs', 'Express Oil Change', 'Scheduled maintenance and inspection'),
    (176, 'Electro Tune', 'Express Oil Change', 'Exterior and interior cleaning services'),
    (177, 'Sparkle Wash', 'Interior Detailing', 'Detailed inspection of brake system'),
    (178, 'Brake Master', 'Coolant Flush', 'Professional coolant system flushing'),
    (179, 'Sparkle Wash', 'Brake Replacement', 'Quick oil change with minimal waiting time'),
    (180, 'Speedy Repairs', 'Express Oil Change', 'Thorough inspection of transmission components'),
    (181, 'Coolant Experts', 'Brake Replacement', 'Quick oil change with minimal waiting time'),
    (182, 'Speedy Repairs', 'Electrical System Check', 'Professional coolant system flushing'),
    (183, 'ABC Service Company', 'Transmission Check', 'Replacement of worn-out brake components'),
    (184, 'Speedy Repairs', 'Regular Maintenance', 'Replacement of worn-out brake components'),
    (185, 'XYZ Repairs', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (186, 'ABC Service Company', 'Brake Replacement', 'Deep cleaning of the vehicle interior'),
    (187, 'Sparkle Wash', 'Transmission Check', 'Deep cleaning of the vehicle interior'),
    (188, 'Speedy Repairs', 'Car Wash', 'Exterior and interior cleaning services'),
    (189, 'Express Oil Change', 'Regular Maintenance', 'Replacement of worn-out brake components'),
    (190, 'QuickOil', 'Car Wash', 'Replacement of worn-out brake components'),
    (191, 'Speedy Repairs', 'Brake Inspection', 'Detailed inspection of brake system'),
    (192, 'Electro Tune', 'Oil Change', 'Quick oil change with minimal waiting time'),
    (193, 'XYZ Repairs', 'Car Wash', 'Deep cleaning of the vehicle interior'),
    (194, 'QuickOil', 'Car Wash', 'Scheduled maintenance and inspection'),
    (195, 'Speedy Repairs', 'Coolant Flush', 'Exterior and interior cleaning services'),
    (196, 'Sunshine Detailing', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (197, 'Brake Master', 'Brake Replacement', 'Scheduled maintenance and inspection'),
    (198, 'Express Oil Change', 'Interior Detailing', 'Exterior and interior cleaning services'),
    (199, 'XYZ Repairs', 'Interior Detailing', 'Scheduled maintenance and inspection'),
    (200, 'Brake Master', 'Interior Detailing', 'Check and repair electrical components'),
    (201, 'Sparkle Wash', 'Brake Replacement', 'Thorough inspection of transmission components'),
    (202, 'Coolant Experts', 'Transmission Check', 'Replacement of worn-out brake components'),
    (203, 'Speedy Repairs', 'Electrical System Check', 'Quick oil change with minimal waiting time'),
    (204, 'XYZ Repairs', 'Express Oil Change', 'Professional coolant system flushing'),
    (205, 'Sparkle Wash', 'Express Oil Change', 'Scheduled maintenance and inspection'),
    (206, 'ABC Service Company', 'Transmission Check', 'Professional coolant system flushing'),
    (207, 'Electro Tune', 'Regular Maintenance', 'Deep cleaning of the vehicle interior'),
    (208, 'Sunshine Detailing', 'Electrical System Check', 'Check and repair electrical components'),
    (209, 'QuickOil', 'Brake Inspection', 'Deep cleaning of the vehicle interior'),
    (210, 'ABC Service Company', 'Brake Replacement', 'Thorough inspection of transmission components'),
    (211, 'Brake Master', 'Express Oil Change', 'Thorough inspection of transmission components'),
    (212, 'Coolant Experts', 'Oil Change', 'Detailed inspection of brake system'),
    (213, 'Brake Master', 'Brake Inspection', 'Fast and efficient oil change service'),
    (214, 'ABC Service Company', 'Oil Change', 'Scheduled maintenance and inspection'),
    (215, 'Brake Master', 'Transmission Check', 'Replacement of worn-out brake components'),
    (216, 'Express Oil Change', 'Express Oil Change', 'Check and repair electrical components'),
    (217, 'Sunshine Detailing', 'Car Wash', 'Fast and efficient oil change service'),
    (218, 'ABC Service Company', 'Regular Maintenance', 'Fast and efficient oil change service'),
    (219, 'Brake Master', 'Coolant Flush', 'Replacement of worn-out brake components'),
    (220, 'Coolant Experts', 'Regular Maintenance', 'Professional coolant system flushing'),
    (221, 'Brake Master', 'Regular Maintenance', 'Scheduled maintenance and inspection'),
    (222, 'Sparkle Wash', 'Interior Detailing', 'Fast and efficient oil change service'),
    (223, 'Sunshine Detailing', 'Regular Maintenance', 'Deep cleaning of the vehicle interior'),
    (224, 'XYZ Repairs', 'Regular Maintenance', 'Scheduled maintenance and inspection'),
    (225, 'XYZ Repairs', 'Regular Maintenance', 'Fast and efficient oil change service'),
    (226, 'Electro Tune', 'Coolant Flush', 'Check and repair electrical components'),
    (227, 'QuickOil', 'Interior Detailing', 'Exterior and interior cleaning services'),
    (228, 'XYZ Repairs', 'Regular Maintenance', 'Fast and efficient oil change service'),
    (229, 'Express Oil Change', 'Interior Detailing', 'Replacement of worn-out brake components'),
    (230, 'Sparkle Wash', 'Interior Detailing', 'Check and repair electrical components'),
    (231, 'Speedy Repairs', 'Transmission Check', 'Replacement of worn-out brake components'),
    (232, 'Brake Master', 'Oil Change', 'Replacement of worn-out brake components'),
    (233, 'XYZ Repairs', 'Brake Inspection', 'Exterior and interior cleaning services'),
    (234, 'XYZ Repairs', 'Car Wash', 'Detailed inspection of brake system'),
    (235, 'XYZ Repairs', 'Electrical System Check', 'Replacement of worn-out brake components'),
    (236, 'Brake Master', 'Car Wash', 'Exterior and interior cleaning services'),
    (237, 'Brake Master', 'Regular Maintenance', 'Exterior and interior cleaning services'),
    (238, 'Sunshine Detailing', 'Express Oil Change', 'Replacement of worn-out brake components'),
    (239, 'Speedy Repairs', 'Car Wash', 'Detailed inspection of brake system'),
    (240, 'Electro Tune', 'Brake Replacement', 'Replacement of worn-out brake components'),
    (241, 'Electro Tune', 'Electrical System Check', 'Quick oil change with minimal waiting time'),
    (242, 'QuickOil', 'Coolant Flush', 'Scheduled maintenance and inspection'),
    (243, 'Electro Tune', 'Electrical System Check', 'Professional coolant system flushing'),
    (244, 'QuickOil', 'Coolant Flush', 'Professional coolant system flushing'),
    (245, 'ABC Service Company', 'Transmission Check', 'Thorough inspection of transmission components'),
    (246, 'Speedy Repairs', 'Interior Detailing', 'Quick oil change with minimal waiting time'),
    (247, 'Speedy Repairs', 'Brake Inspection', 'Check and repair electrical components'),
    (248, 'Speedy Repairs', 'Brake Replacement', 'Quick oil change with minimal waiting time'),
    (249, 'Sunshine Detailing', 'Brake Inspection', 'Deep cleaning of the vehicle interior'),
    (250, 'QuickOil', 'Electrical System Check', 'Professional coolant system flushing'),
    (251, 'Coolant Experts', 'Electrical System Check', 'Thorough inspection of transmission components'),
    (252, 'Coolant Experts', 'Coolant Flush', 'Thorough inspection of transmission components'),
    (253, 'XYZ Repairs', 'Coolant Flush', 'Thorough inspection of transmission components'),
    (254, 'Sparkle Wash', 'Car Wash', 'Replacement of worn-out brake components'),
    (255, 'ABC Service Company', 'Interior Detailing', 'Quick oil change with minimal waiting time'),
    (256, 'Sunshine Detailing', 'Express Oil Change', 'Replacement of worn-out brake components'),
    (257, 'Sparkle Wash', 'Coolant Flush', 'Replacement of worn-out brake components'),
    (258, 'Electro Tune', 'Brake Replacement', 'Thorough inspection of transmission components'),
    (259, 'Electro Tune', 'Brake Replacement', 'Professional coolant system flushing'),
    (260, 'Sunshine Detailing', 'Brake Inspection', 'Detailed inspection of brake system'),
    (261, 'Sunshine Detailing', 'Regular Maintenance', 'Quick oil change with minimal waiting time'),
    (262, 'Sunshine Detailing', 'Brake Replacement', 'Check and repair electrical components'),
    (263, 'Speedy Repairs', 'Regular Maintenance', 'Quick oil change with minimal waiting time'),
    (264, 'Express Oil Change', 'Brake Replacement', 'Exterior and interior cleaning services'),
    (265, 'Brake Master', 'Oil Change', 'Fast and efficient oil change service'),
    (266, 'Coolant Experts', 'Brake Inspection', 'Replacement of worn-out brake components'),
    (267, 'ABC Service Company', 'Transmission Check', 'Thorough inspection of transmission components'),
    (268, 'Sunshine Detailing', 'Brake Inspection', 'Scheduled maintenance and inspection'),
    (269, 'QuickOil', 'Express Oil Change', 'Exterior and interior cleaning services'),
    (270, 'Electro Tune', 'Regular Maintenance', 'Deep cleaning of the vehicle interior'),
    (271, 'QuickOil', 'Brake Inspection', 'Deep cleaning of the vehicle interior'),
    (272, 'Express Oil Change', 'Car Wash', 'Fast and efficient oil change service'),
    (273, 'Electro Tune', 'Interior Detailing', 'Quick oil change with minimal waiting time'),
    (274, 'Sunshine Detailing', 'Transmission Check', 'Scheduled maintenance and inspection'),
    (275, 'ABC Service Company', 'Transmission Check', 'Exterior and interior cleaning services'),
    (276, 'QuickOil', 'Oil Change', 'Fast and efficient oil change service'),
    (277, 'QuickOil', 'Brake Replacement', 'Check and repair electrical components'),
    (278, 'Electro Tune', 'Interior Detailing', 'Thorough inspection of transmission components'),
    (279, 'ABC Service Company', 'Electrical System Check', 'Professional coolant system flushing'),
    (280, 'Coolant Experts', 'Interior Detailing', 'Check and repair electrical components'),
    (281, 'Express Oil Change', 'Electrical System Check', 'Quick oil change with minimal waiting time'),
    (282, 'Express Oil Change', 'Brake Replacement', 'Check and repair electrical components'),
    (283, 'XYZ Repairs', 'Oil Change', 'Deep cleaning of the vehicle interior'),
    (284, 'ABC Service Company', 'Coolant Flush', 'Scheduled maintenance and inspection'),
    (285, 'Sunshine Detailing', 'Car Wash', 'Exterior and interior cleaning services'),
    (286, 'XYZ Repairs', 'Brake Replacement', 'Thorough inspection of transmission components'),
    (287, 'Coolant Experts', 'Interior Detailing', 'Exterior and interior cleaning services'),
    (288, 'QuickOil', 'Regular Maintenance', 'Deep cleaning of the vehicle interior'),
    (289, 'ABC Service Company', 'Electrical System Check', 'Thorough inspection of transmission components'),
    (290, 'Electro Tune', 'Coolant Flush', 'Quick oil change with minimal waiting time'),
    (291, 'Sparkle Wash', 'Regular Maintenance', 'Check and repair electrical components'),
    (292, 'QuickOil', 'Express Oil Change', 'Deep cleaning of the vehicle interior'),
    (293, 'Speedy Repairs', 'Express Oil Change', 'Thorough inspection of transmission components'),
    (294, 'Express Oil Change', 'Express Oil Change', 'Replacement of worn-out brake components'),
    (295, 'Express Oil Change', 'Brake Inspection', 'Scheduled maintenance and inspection'),
    (296, 'ABC Service Company', 'Oil Change', 'Deep cleaning of the vehicle interior'),
    (297, 'Electro Tune', 'Oil Change', 'Replacement of worn-out brake components'),
    (298, 'Sparkle Wash', 'Car Wash', 'Detailed inspection of brake system'),
    (299, 'Electro Tune', 'Car Wash', 'Professional coolant system flushing'),
    (300, 'Speedy Repairs', 'Brake Replacement', 'Replacement of worn-out brake components'),
    (301, 'QuickOil', 'Brake Replacement', 'Scheduled maintenance and inspection'),
    (302, 'Sunshine Detailing', 'Coolant Flush', 'Check and repair electrical components'),
    (303, 'Electro Tune', 'Brake Replacement', 'Thorough inspection of transmission components'),
    (304, 'Brake Master', 'Coolant Flush', 'Check and repair electrical components'),
    (305, 'Sparkle Wash', 'Interior Detailing', 'Professional coolant system flushing'),
    (306, 'Speedy Repairs', 'Electrical System Check', 'Deep cleaning of the vehicle interior'),
    (307, 'Express Oil Change', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (308, 'Coolant Experts', 'Interior Detailing', 'Replacement of worn-out brake components'),
    (309, 'Express Oil Change', 'Brake Inspection', 'Exterior and interior cleaning services'),
    (310, 'Brake Master', 'Brake Replacement', 'Detailed inspection of brake system'),
    (311, 'Sparkle Wash', 'Transmission Check', 'Exterior and interior cleaning services'),
    (312, 'ABC Service Company', 'Brake Replacement', 'Exterior and interior cleaning services'),
    (313, 'XYZ Repairs', 'Oil Change', 'Quick oil change with minimal waiting time'),
    (314, 'Express Oil Change', 'Car Wash', 'Quick oil change with minimal waiting time'),
    (315, 'QuickOil', 'Car Wash', 'Scheduled maintenance and inspection'),
    (316, 'ABC Service Company', 'Regular Maintenance', 'Replacement of worn-out brake components'),
    (317, 'Brake Master', 'Brake Replacement', 'Quick oil change with minimal waiting time'),
    (318, 'Coolant Experts', 'Regular Maintenance', 'Thorough inspection of transmission components'),
    (319, 'QuickOil', 'Coolant Flush', 'Scheduled maintenance and inspection'),
    (320, 'Coolant Experts', 'Regular Maintenance', 'Fast and efficient oil change service'),
    (321, 'Sunshine Detailing', 'Interior Detailing', 'Professional coolant system flushing'),
    (322, 'ABC Service Company', 'Regular Maintenance', 'Quick oil change with minimal waiting time'),
    (323, 'Speedy Repairs', 'Coolant Flush', 'Replacement of worn-out brake components'),
    (324, 'QuickOil', 'Transmission Check', 'Detailed inspection of brake system'),
    (325, 'Sunshine Detailing', 'Electrical System Check', 'Exterior and interior cleaning services'),
    (326, 'QuickOil', 'Brake Inspection', 'Check and repair electrical components'),
    (327, 'Electro Tune', 'Oil Change', 'Replacement of worn-out brake components'),
    (328, 'Coolant Experts', 'Regular Maintenance', 'Check and repair electrical components'),
    (329, 'Express Oil Change', 'Brake Replacement', 'Exterior and interior cleaning services'),
    (330, 'Sunshine Detailing', 'Brake Replacement', 'Check and repair electrical components'),
    (331, 'ABC Service Company', 'Coolant Flush', 'Check and repair electrical components'),
    (332, 'Speedy Repairs', 'Brake Replacement', 'Exterior and interior cleaning services'),
    (333, 'Electro Tune', 'Interior Detailing', 'Thorough inspection of transmission components'),
    (334, 'Sparkle Wash', 'Brake Replacement', 'Check and repair electrical components'),
    (335, 'Express Oil Change', 'Transmission Check', 'Exterior and interior cleaning services'),
    (336, 'QuickOil', 'Brake Inspection', 'Check and repair electrical components'),
    (337, 'Sunshine Detailing', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (338, 'Sunshine Detailing', 'Regular Maintenance', 'Professional coolant system flushing'),
    (339, 'Speedy Repairs', 'Express Oil Change', 'Detailed inspection of brake system'),
    (340, 'Electro Tune', 'Electrical System Check', 'Professional coolant system flushing'),
    (341, 'QuickOil', 'Regular Maintenance', 'Replacement of worn-out brake components'),
    (342, 'Electro Tune', 'Electrical System Check', 'Exterior and interior cleaning services'),
    (343, 'Express Oil Change', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (344, 'Speedy Repairs', 'Electrical System Check', 'Exterior and interior cleaning services'),
    (345, 'ABC Service Company', 'Car Wash', 'Thorough inspection of transmission components'),
    (346, 'Sunshine Detailing', 'Regular Maintenance', 'Exterior and interior cleaning services'),
    (347, 'QuickOil', 'Brake Replacement', 'Professional coolant system flushing'),
    (348, 'ABC Service Company', 'Electrical System Check', 'Fast and efficient oil change service'),
    (349, 'Express Oil Change', 'Coolant Flush', 'Quick oil change with minimal waiting time'),
    (350, 'Electro Tune', 'Car Wash', 'Thorough inspection of transmission components'),
    (351, 'QuickOil', 'Brake Inspection', 'Scheduled maintenance and inspection'),
    (352, 'QuickOil', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (353, 'Sparkle Wash', 'Regular Maintenance', 'Exterior and interior cleaning services'),
    (354, 'Electro Tune', 'Regular Maintenance', 'Check and repair electrical components'),
    (355, 'XYZ Repairs', 'Brake Inspection', 'Quick oil change with minimal waiting time'),
    (356, 'Sunshine Detailing', 'Interior Detailing', 'Check and repair electrical components'),
    (357, 'XYZ Repairs', 'Oil Change', 'Check and repair electrical components'),
    (358, 'QuickOil', 'Brake Inspection', 'Fast and efficient oil change service'),
    (359, 'Brake Master', 'Oil Change', 'Scheduled maintenance and inspection'),
    (360, 'Coolant Experts', 'Coolant Flush', 'Thorough inspection of transmission components'),
    (361, 'QuickOil', 'Brake Inspection', 'Detailed inspection of brake system'),
    (362, 'Brake Master', 'Regular Maintenance', 'Deep cleaning of the vehicle interior'),
    (363, 'ABC Service Company', 'Transmission Check', 'Professional coolant system flushing'),
    (364, 'Express Oil Change', 'Oil Change', 'Scheduled maintenance and inspection'),
    (365, 'Coolant Experts', 'Transmission Check', 'Replacement of worn-out brake components'),
    (366, 'Sunshine Detailing', 'Brake Inspection', 'Replacement of worn-out brake components'),
    (367, 'Electro Tune', 'Electrical System Check', 'Quick oil change with minimal waiting time'),
    (368, 'Coolant Experts', 'Coolant Flush', 'Check and repair electrical components'),
    (369, 'Sunshine Detailing', 'Electrical System Check', 'Replacement of worn-out brake components'),
    (370, 'QuickOil', 'Oil Change', 'Deep cleaning of the vehicle interior'),
    (371, 'Electro Tune', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (372, 'Coolant Experts', 'Brake Inspection', 'Replacement of worn-out brake components'),
    (373, 'Coolant Experts', 'Car Wash', 'Thorough inspection of transmission components'),
    (374, 'QuickOil', 'Express Oil Change', 'Deep cleaning of the vehicle interior'),
    (375, 'XYZ Repairs', 'Brake Inspection', 'Quick oil change with minimal waiting time'),
    (376, 'Speedy Repairs', 'Express Oil Change', 'Deep cleaning of the vehicle interior'),
    (377, 'XYZ Repairs', 'Car Wash', 'Detailed inspection of brake system'),
    (378, 'Sunshine Detailing', 'Coolant Flush', 'Thorough inspection of transmission components'),
    (379, 'Express Oil Change', 'Oil Change', 'Deep cleaning of the vehicle interior'),
    (380, 'XYZ Repairs', 'Brake Inspection', 'Quick oil change with minimal waiting time'),
    (381, 'ABC Service Company', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (382, 'Sunshine Detailing', 'Brake Inspection', 'Detailed inspection of brake system'),
    (383, 'QuickOil', 'Brake Replacement', 'Exterior and interior cleaning services'),
    (384, 'ABC Service Company', 'Electrical System Check', 'Scheduled maintenance and inspection'),
    (385, 'Sunshine Detailing', 'Electrical System Check', 'Quick oil change with minimal waiting time'),
    (386, 'Brake Master', 'Electrical System Check', 'Quick oil change with minimal waiting time'),
    (387, 'Brake Master', 'Brake Inspection', 'Fast and efficient oil change service'),
    (388, 'Electro Tune', 'Electrical System Check', 'Professional coolant system flushing'),
    (389, 'Sunshine Detailing', 'Oil Change', 'Detailed inspection of brake system'),
    (390, 'Speedy Repairs', 'Transmission Check', 'Detailed inspection of brake system'),
    (391, 'QuickOil', 'Car Wash', 'Thorough inspection of transmission components'),
    (392, 'Express Oil Change', 'Express Oil Change', 'Quick oil change with minimal waiting time'),
    (393, 'XYZ Repairs', 'Car Wash', 'Replacement of worn-out brake components'),
    (394, 'Express Oil Change', 'Transmission Check', 'Deep cleaning of the vehicle interior'),
    (395, 'Speedy Repairs', 'Oil Change', 'Detailed inspection of brake system'),
    (396, 'ABC Service Company', 'Car Wash', 'Deep cleaning of the vehicle interior'),
    (397, 'XYZ Repairs', 'Express Oil Change', 'Scheduled maintenance and inspection'),
    (398, 'Sunshine Detailing', 'Car Wash', 'Scheduled maintenance and inspection'),
    (399, 'Coolant Experts', 'Transmission Check', 'Scheduled maintenance and inspection'),
    (400, 'QuickOil', 'Coolant Flush', 'Quick oil change with minimal waiting time'),
    (401, 'QuickOil', 'Car Wash', 'Detailed inspection of brake system'),
    (402, 'QuickOil', 'Brake Replacement', 'Professional coolant system flushing'),
    (403, 'XYZ Repairs', 'Regular Maintenance', 'Scheduled maintenance and inspection'),
    (404, 'Sunshine Detailing', 'Brake Inspection', 'Thorough inspection of transmission components'),
    (405, 'Sunshine Detailing', 'Coolant Flush', 'Detailed inspection of brake system'),
    (406, 'QuickOil', 'Regular Maintenance', 'Exterior and interior cleaning services'),
    (407, 'Coolant Experts', 'Transmission Check', 'Thorough inspection of transmission components'),
    (408, 'QuickOil', 'Brake Replacement', 'Replacement of worn-out brake components'),
    (409, 'Brake Master', 'Brake Inspection', 'Scheduled maintenance and inspection'),
    (410, 'Electro Tune', 'Brake Inspection', 'Deep cleaning of the vehicle interior'),
    (411, 'ABC Service Company', 'Car Wash', 'Check and repair electrical components'),
    (412, 'Electro Tune', 'Interior Detailing', 'Detailed inspection of brake system'),
    (413, 'ABC Service Company', 'Brake Replacement', 'Scheduled maintenance and inspection'),
    (414, 'Speedy Repairs', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (415, 'Coolant Experts', 'Regular Maintenance', 'Professional coolant system flushing'),
    (416, 'QuickOil', 'Oil Change', 'Detailed inspection of brake system'),
    (417, 'XYZ Repairs', 'Transmission Check', 'Thorough inspection of transmission components'),
    (418, 'Express Oil Change', 'Express Oil Change', 'Check and repair electrical components'),
    (419, 'Speedy Repairs', 'Electrical System Check', 'Scheduled maintenance and inspection'),
    (420, 'QuickOil', 'Brake Replacement', 'Professional coolant system flushing'),
    (421, 'Brake Master', 'Coolant Flush', 'Thorough inspection of transmission components'),
    (422, 'Express Oil Change', 'Transmission Check', 'Check and repair electrical components'),
    (423, 'XYZ Repairs', 'Transmission Check', 'Fast and efficient oil change service'),
    (424, 'Sunshine Detailing', 'Express Oil Change', 'Exterior and interior cleaning services'),
    (425, 'QuickOil', 'Brake Inspection', 'Thorough inspection of transmission components'),
    (426, 'Sparkle Wash', 'Oil Change', 'Quick oil change with minimal waiting time'),
    (427, 'Electro Tune', 'Regular Maintenance', 'Replacement of worn-out brake components'),
    (428, 'Brake Master', 'Regular Maintenance', 'Fast and efficient oil change service'),
    (429, 'Coolant Experts', 'Brake Replacement', 'Professional coolant system flushing'),
    (430, 'Coolant Experts', 'Oil Change', 'Replacement of worn-out brake components'),
    (431, 'Coolant Experts', 'Coolant Flush', 'Fast and efficient oil change service'),
    (432, 'Sparkle Wash', 'Transmission Check', 'Thorough inspection of transmission components'),
    (433, 'Express Oil Change', 'Interior Detailing', 'Quick oil change with minimal waiting time'),
    (434, 'XYZ Repairs', 'Car Wash', 'Detailed inspection of brake system'),
    (435, 'Speedy Repairs', 'Brake Replacement', 'Exterior and interior cleaning services'),
    (436, 'Electro Tune', 'Oil Change', 'Detailed inspection of brake system'),
    (437, 'Speedy Repairs', 'Transmission Check', 'Deep cleaning of the vehicle interior'),
    (438, 'Coolant Experts', 'Express Oil Change', 'Check and repair electrical components'),
    (439, 'Electro Tune', 'Transmission Check', 'Check and repair electrical components'),
    (440, 'Brake Master', 'Express Oil Change', 'Quick oil change with minimal waiting time'),
    (441, 'XYZ Repairs', 'Interior Detailing', 'Professional coolant system flushing'),
    (442, 'Sunshine Detailing', 'Brake Inspection', 'Quick oil change with minimal waiting time'),
    (443, 'Brake Master', 'Brake Replacement', 'Replacement of worn-out brake components'),
    (444, 'Express Oil Change', 'Oil Change', 'Quick oil change with minimal waiting time'),
    (445, 'ABC Service Company', 'Interior Detailing', 'Thorough inspection of transmission components'),
    (446, 'Brake Master', 'Interior Detailing', 'Exterior and interior cleaning services'),
    (447, 'Sparkle Wash', 'Brake Replacement', 'Fast and efficient oil change service'),
    (448, 'XYZ Repairs', 'Oil Change', 'Scheduled maintenance and inspection'),
    (449, 'Express Oil Change', 'Brake Inspection', 'Check and repair electrical components'),
    (450, 'QuickOil', 'Oil Change', 'Replacement of worn-out brake components'),
    (451, 'Brake Master', 'Brake Inspection', 'Check and repair electrical components'),
    (452, 'QuickOil', 'Coolant Flush', 'Fast and efficient oil change service'),
    (453, 'Brake Master', 'Brake Replacement', 'Professional coolant system flushing'),
    (454, 'Coolant Experts', 'Transmission Check', 'Deep cleaning of the vehicle interior'),
    (455, 'Electro Tune', 'Express Oil Change', 'Professional coolant system flushing'),
    (456, 'Speedy Repairs', 'Oil Change', 'Replacement of worn-out brake components'),
    (457, 'Sparkle Wash', 'Electrical System Check', 'Scheduled maintenance and inspection'),
    (458, 'XYZ Repairs', 'Brake Replacement', 'Replacement of worn-out brake components'),
    (459, 'ABC Service Company', 'Brake Inspection', 'Replacement of worn-out brake components'),
    (460, 'QuickOil', 'Regular Maintenance', 'Check and repair electrical components'),
    (461, 'Coolant Experts', 'Interior Detailing', 'Detailed inspection of brake system'),
    (462, 'Sparkle Wash', 'Car Wash', 'Fast and efficient oil change service'),
    (463, 'QuickOil', 'Oil Change', 'Replacement of worn-out brake components'),
    (464, 'Express Oil Change', 'Transmission Check', 'Deep cleaning of the vehicle interior'),
    (465, 'Express Oil Change', 'Interior Detailing', 'Exterior and interior cleaning services'),
    (466, 'XYZ Repairs', 'Transmission Check', 'Replacement of worn-out brake components'),
    (467, 'Express Oil Change', 'Car Wash', 'Quick oil change with minimal waiting time'),
    (468, 'XYZ Repairs', 'Oil Change', 'Professional coolant system flushing'),
    (469, 'XYZ Repairs', 'Transmission Check', 'Deep cleaning of the vehicle interior'),
    (470, 'Electro Tune', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (471, 'Electro Tune', 'Brake Replacement', 'Professional coolant system flushing'),
    (472, 'Brake Master', 'Electrical System Check', 'Exterior and interior cleaning services'),
    (473, 'Sparkle Wash', 'Coolant Flush', 'Detailed inspection of brake system'),
    (474, 'ABC Service Company', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (475, 'Sunshine Detailing', 'Express Oil Change', 'Thorough inspection of transmission components'),
    (476, 'Express Oil Change', 'Transmission Check', 'Professional coolant system flushing'),
    (477, 'Sunshine Detailing', 'Interior Detailing', 'Replacement of worn-out brake components'),
    (478, 'XYZ Repairs', 'Brake Replacement', 'Professional coolant system flushing'),
    (479, 'ABC Service Company', 'Electrical System Check', 'Fast and efficient oil change service'),
    (480, 'Speedy Repairs', 'Interior Detailing', 'Exterior and interior cleaning services'),
    (481, 'XYZ Repairs', 'Brake Inspection', 'Detailed inspection of brake system'),
    (482, 'Electro Tune', 'Brake Inspection', 'Fast and efficient oil change service'),
    (483, 'ABC Service Company', 'Electrical System Check', 'Check and repair electrical components'),
    (484, 'QuickOil', 'Brake Inspection', 'Deep cleaning of the vehicle interior'),
    (485, 'ABC Service Company', 'Car Wash', 'Scheduled maintenance and inspection'),
    (486, 'Sunshine Detailing', 'Interior Detailing', 'Professional coolant system flushing'),
    (487, 'Brake Master', 'Transmission Check', 'Check and repair electrical components'),
    (488, 'Speedy Repairs', 'Coolant Flush', 'Fast and efficient oil change service'),
    (489, 'Sparkle Wash', 'Express Oil Change', 'Exterior and interior cleaning services'),
    (490, 'Speedy Repairs', 'Regular Maintenance', 'Scheduled maintenance and inspection'),
    (491, 'XYZ Repairs', 'Oil Change', 'Thorough inspection of transmission components'),
    (492, 'Brake Master', 'Coolant Flush', 'Detailed inspection of brake system'),
    (493, 'QuickOil', 'Regular Maintenance', 'Thorough inspection of transmission components'),
    (494, 'Electro Tune', 'Interior Detailing', 'Scheduled maintenance and inspection'),
    (495, 'Speedy Repairs', 'Express Oil Change', 'Detailed inspection of brake system'),
    (496, 'Electro Tune', 'Regular Maintenance', 'Fast and efficient oil change service'),
    (497, 'Sparkle Wash', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (498, 'Brake Master', 'Brake Replacement', 'Detailed inspection of brake system'),
    (499, 'XYZ Repairs', 'Oil Change', 'Professional coolant system flushing'),
    (500, 'Sparkle Wash', 'Oil Change', 'Scheduled maintenance and inspection'),
    (501, 'Express Oil Change', 'Express Oil Change', 'Quick oil change with minimal waiting time'),
    (502, 'Electro Tune', 'Express Oil Change', 'Exterior and interior cleaning services'),
    (503, 'XYZ Repairs', 'Transmission Check', 'Quick oil change with minimal waiting time'),
    (504, 'Coolant Experts', 'Brake Replacement', 'Replacement of worn-out brake components'),
    (505, 'Speedy Repairs', 'Interior Detailing', 'Detailed inspection of brake system'),
    (506, 'QuickOil', 'Electrical System Check', 'Replacement of worn-out brake components'),
    (507, 'Speedy Repairs', 'Interior Detailing', 'Exterior and interior cleaning services'),
    (508, 'Express Oil Change', 'Regular Maintenance', 'Check and repair electrical components'),
    (509, 'Coolant Experts', 'Coolant Flush', 'Thorough inspection of transmission components'),
    (510, 'Sunshine Detailing', 'Express Oil Change', 'Fast and efficient oil change service'),
    (511, 'Electro Tune', 'Brake Replacement', 'Exterior and interior cleaning services'),
    (512, 'Express Oil Change', 'Brake Inspection', 'Fast and efficient oil change service'),
    (513, 'Brake Master', 'Brake Inspection', 'Detailed inspection of brake system'),
    (514, 'Sparkle Wash', 'Coolant Flush', 'Exterior and interior cleaning services'),
    (515, 'Brake Master', 'Transmission Check', 'Deep cleaning of the vehicle interior'),
    (516, 'Speedy Repairs', 'Express Oil Change', 'Professional coolant system flushing'),
    (517, 'Electro Tune', 'Transmission Check', 'Quick oil change with minimal waiting time'),
    (518, 'Coolant Experts', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (519, 'Electro Tune', 'Brake Inspection', 'Thorough inspection of transmission components'),
    (520, 'XYZ Repairs', 'Transmission Check', 'Replacement of worn-out brake components'),
    (521, 'Electro Tune', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (522, 'Sunshine Detailing', 'Regular Maintenance', 'Check and repair electrical components'),
    (523, 'Express Oil Change', 'Coolant Flush', 'Thorough inspection of transmission components'),
    (524, 'QuickOil', 'Electrical System Check', 'Thorough inspection of transmission components'),
    (525, 'Sparkle Wash', 'Regular Maintenance', 'Replacement of worn-out brake components'),
    (526, 'Speedy Repairs', 'Transmission Check', 'Thorough inspection of transmission components'),
    (527, 'XYZ Repairs', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (528, 'Speedy Repairs', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (529, 'ABC Service Company', 'Regular Maintenance', 'Replacement of worn-out brake components'),
    (530, 'QuickOil', 'Regular Maintenance', 'Scheduled maintenance and inspection'),
    (531, 'Sparkle Wash', 'Transmission Check', 'Deep cleaning of the vehicle interior'),
    (532, 'ABC Service Company', 'Electrical System Check', 'Fast and efficient oil change service'),
    (533, 'Electro Tune', 'Transmission Check', 'Fast and efficient oil change service'),
    (534, 'ABC Service Company', 'Brake Inspection', 'Quick oil change with minimal waiting time'),
    (535, 'Sparkle Wash', 'Brake Inspection', 'Fast and efficient oil change service'),
    (536, 'Express Oil Change', 'Express Oil Change', 'Thorough inspection of transmission components'),
    (537, 'ABC Service Company', 'Interior Detailing', 'Check and repair electrical components'),
    (538, 'QuickOil', 'Brake Replacement', 'Scheduled maintenance and inspection'),
    (539, 'Sunshine Detailing', 'Express Oil Change', 'Replacement of worn-out brake components'),
    (540, 'Sunshine Detailing', 'Transmission Check', 'Check and repair electrical components'),
    (541, 'Brake Master', 'Brake Replacement', 'Exterior and interior cleaning services'),
    (542, 'QuickOil', 'Express Oil Change', 'Scheduled maintenance and inspection'),
    (543, 'QuickOil', 'Interior Detailing', 'Thorough inspection of transmission components'),
    (544, 'Brake Master', 'Regular Maintenance', 'Replacement of worn-out brake components'),
    (545, 'Electro Tune', 'Electrical System Check', 'Professional coolant system flushing'),
    (546, 'XYZ Repairs', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (547, 'XYZ Repairs', 'Regular Maintenance', 'Professional coolant system flushing'),
    (548, 'Sparkle Wash', 'Regular Maintenance', 'Thorough inspection of transmission components'),
    (549, 'Express Oil Change', 'Car Wash', 'Deep cleaning of the vehicle interior'),
    (550, 'XYZ Repairs', 'Oil Change', 'Detailed inspection of brake system'),
    (551, 'Express Oil Change', 'Car Wash', 'Quick oil change with minimal waiting time'),
    (552, 'Express Oil Change', 'Brake Replacement', 'Deep cleaning of the vehicle interior'),
    (553, 'Sparkle Wash', 'Oil Change', 'Fast and efficient oil change service'),
    (554, 'Express Oil Change', 'Car Wash', 'Detailed inspection of brake system'),
    (555, 'XYZ Repairs', 'Car Wash', 'Scheduled maintenance and inspection'),
    (556, 'Electro Tune', 'Brake Replacement', 'Deep cleaning of the vehicle interior'),
    (557, 'ABC Service Company', 'Brake Replacement', 'Thorough inspection of transmission components'),
    (558, 'Speedy Repairs', 'Regular Maintenance', 'Fast and efficient oil change service'),
    (559, 'XYZ Repairs', 'Brake Replacement', 'Replacement of worn-out brake components'),
    (560, 'Electro Tune', 'Car Wash', 'Deep cleaning of the vehicle interior'),
    (561, 'XYZ Repairs', 'Brake Inspection', 'Scheduled maintenance and inspection'),
    (562, 'Coolant Experts', 'Express Oil Change', 'Quick oil change with minimal waiting time'),
    (563, 'Express Oil Change', 'Express Oil Change', 'Thorough inspection of transmission components'),
    (564, 'ABC Service Company', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (565, 'Speedy Repairs', 'Brake Replacement', 'Detailed inspection of brake system'),
    (566, 'ABC Service Company', 'Electrical System Check', 'Quick oil change with minimal waiting time'),
    (567, 'Brake Master', 'Brake Replacement', 'Thorough inspection of transmission components'),
    (568, 'Speedy Repairs', 'Oil Change', 'Fast and efficient oil change service'),
    (569, 'Sunshine Detailing', 'Car Wash', 'Quick oil change with minimal waiting time'),
    (570, 'Coolant Experts', 'Regular Maintenance', 'Professional coolant system flushing'),
    (571, 'Sparkle Wash', 'Car Wash', 'Deep cleaning of the vehicle interior'),
    (572, 'Sparkle Wash', 'Oil Change', 'Check and repair electrical components'),
    (573, 'Express Oil Change', 'Interior Detailing', 'Thorough inspection of transmission components'),
    (574, 'QuickOil', 'Transmission Check', 'Replacement of worn-out brake components'),
    (575, 'Coolant Experts', 'Coolant Flush', 'Fast and efficient oil change service'),
    (576, 'ABC Service Company', 'Interior Detailing', 'Scheduled maintenance and inspection'),
    (577, 'Brake Master', 'Transmission Check', 'Professional coolant system flushing'),
    (578, 'XYZ Repairs', 'Oil Change', 'Replacement of worn-out brake components'),
    (579, 'Coolant Experts', 'Oil Change', 'Deep cleaning of the vehicle interior'),
    (580, 'Brake Master', 'Interior Detailing', 'Quick oil change with minimal waiting time'),
    (581, 'Electro Tune', 'Regular Maintenance', 'Exterior and interior cleaning services'),
    (582, 'Express Oil Change', 'Express Oil Change', 'Deep cleaning of the vehicle interior'),
    (583, 'Electro Tune', 'Brake Replacement', 'Professional coolant system flushing'),
    (584, 'Express Oil Change', 'Coolant Flush', 'Exterior and interior cleaning services'),
    (585, 'QuickOil', 'Regular Maintenance', 'Fast and efficient oil change service'),
    (586, 'Coolant Experts', 'Express Oil Change', 'Scheduled maintenance and inspection'),
    (587, 'Express Oil Change', 'Express Oil Change', 'Check and repair electrical components'),
    (588, 'Speedy Repairs', 'Electrical System Check', 'Exterior and interior cleaning services'),
    (589, 'Electro Tune', 'Express Oil Change', 'Replacement of worn-out brake components'),
    (590, 'Express Oil Change', 'Electrical System Check', 'Replacement of worn-out brake components'),
    (591, 'Coolant Experts', 'Brake Replacement', 'Fast and efficient oil change service'),
    (592, 'Coolant Experts', 'Car Wash', 'Fast and efficient oil change service'),
    (593, 'Sunshine Detailing', 'Electrical System Check', 'Detailed inspection of brake system'),
    (594, 'Speedy Repairs', 'Brake Replacement', 'Professional coolant system flushing'),
    (595, 'Express Oil Change', 'Oil Change', 'Quick oil change with minimal waiting time'),
    (596, 'ABC Service Company', 'Oil Change', 'Replacement of worn-out brake components'),
    (597, 'Electro Tune', 'Brake Inspection', 'Professional coolant system flushing'),
    (598, 'Coolant Experts', 'Transmission Check', 'Check and repair electrical components'),
    (599, 'XYZ Repairs', 'Brake Inspection', 'Detailed inspection of brake system'),
    (600, 'Express Oil Change', 'Interior Detailing', 'Deep cleaning of the vehicle interior'),
    (601, 'Sunshine Detailing', 'Transmission Check', 'Fast and efficient oil change service'),
    (602, 'Brake Master', 'Brake Replacement', 'Deep cleaning of the vehicle interior'),
    (603, 'Sunshine Detailing', 'Brake Inspection', 'Check and repair electrical components'),
    (604, 'Brake Master', 'Express Oil Change', 'Scheduled maintenance and inspection'),
    (605, 'Sparkle Wash', 'Coolant Flush', 'Exterior and interior cleaning services'),
    (606, 'XYZ Repairs', 'Car Wash', 'Scheduled maintenance and inspection'),
    (607, 'Sparkle Wash', 'Brake Replacement', 'Exterior and interior cleaning services'),
    (608, 'XYZ Repairs', 'Regular Maintenance', 'Check and repair electrical components'),
    (609, 'QuickOil', 'Coolant Flush', 'Scheduled maintenance and inspection'),
    (610, 'Electro Tune', 'Electrical System Check', 'Quick oil change with minimal waiting time'),
    (611, 'Express Oil Change', 'Oil Change', 'Fast and efficient oil change service'),
    (612, 'Sunshine Detailing', 'Express Oil Change', 'Thorough inspection of transmission components'),
    (613, 'Electro Tune', 'Transmission Check', 'Fast and efficient oil change service'),
    (614, 'ABC Service Company', 'Coolant Flush', 'Quick oil change with minimal waiting time'),
    (615, 'Sparkle Wash', 'Oil Change', 'Check and repair electrical components'),
    (616, 'Coolant Experts', 'Coolant Flush', 'Thorough inspection of transmission components'),
    (617, 'Brake Master', 'Transmission Check', 'Detailed inspection of brake system'),
    (618, 'Electro Tune', 'Oil Change', 'Replacement of worn-out brake components'),
    (619, 'Express Oil Change', 'Electrical System Check', 'Professional coolant system flushing'),
    (620, 'Coolant Experts', 'Car Wash', 'Thorough inspection of transmission components'),
    (621, 'XYZ Repairs', 'Car Wash', 'Exterior and interior cleaning services'),
    (622, 'Coolant Experts', 'Oil Change', 'Thorough inspection of transmission components'),
    (623, 'Electro Tune', 'Car Wash', 'Scheduled maintenance and inspection'),
    (624, 'Sunshine Detailing', 'Regular Maintenance', 'Fast and efficient oil change service'),
    (625, 'Sunshine Detailing', 'Express Oil Change', 'Detailed inspection of brake system'),
    (626, 'Sunshine Detailing', 'Coolant Flush', 'Thorough inspection of transmission components'),
    (627, 'Sunshine Detailing', 'Brake Inspection', 'Check and repair electrical components'),
    (628, 'Sparkle Wash', 'Transmission Check', 'Exterior and interior cleaning services'),
    (629, 'Sparkle Wash', 'Express Oil Change', 'Scheduled maintenance and inspection'),
    (630, 'Speedy Repairs', 'Brake Replacement', 'Thorough inspection of transmission components'),
    (631, 'Brake Master', 'Express Oil Change', 'Fast and efficient oil change service'),
    (632, 'Express Oil Change', 'Express Oil Change', 'Exterior and interior cleaning services'),
    (633, 'Sparkle Wash', 'Express Oil Change', 'Fast and efficient oil change service'),
    (634, 'Express Oil Change', 'Express Oil Change', 'Quick oil change with minimal waiting time'),
    (635, 'Coolant Experts', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (636, 'Electro Tune', 'Brake Inspection', 'Quick oil change with minimal waiting time'),
    (637, 'Brake Master', 'Transmission Check', 'Professional coolant system flushing'),
    (638, 'ABC Service Company', 'Regular Maintenance', 'Professional coolant system flushing'),
    (639, 'Express Oil Change', 'Car Wash', 'Fast and efficient oil change service'),
    (640, 'Sunshine Detailing', 'Electrical System Check', 'Exterior and interior cleaning services'),
    (641, 'Express Oil Change', 'Interior Detailing', 'Check and repair electrical components'),
    (642, 'ABC Service Company', 'Brake Replacement', 'Exterior and interior cleaning services'),
    (643, 'QuickOil', 'Express Oil Change', 'Quick oil change with minimal waiting time'),
    (644, 'Express Oil Change', 'Coolant Flush', 'Replacement of worn-out brake components'),
    (645, 'Electro Tune', 'Oil Change', 'Scheduled maintenance and inspection'),
    (646, 'XYZ Repairs', 'Brake Inspection', 'Check and repair electrical components'),
    (647, 'Express Oil Change', 'Interior Detailing', 'Check and repair electrical components'),
    (648, 'Speedy Repairs', 'Interior Detailing', 'Detailed inspection of brake system'),
    (649, 'XYZ Repairs', 'Coolant Flush', 'Exterior and interior cleaning services'),
    (650, 'QuickOil', 'Oil Change', 'Detailed inspection of brake system'),
    (651, 'ABC Service Company', 'Oil Change', 'Fast and efficient oil change service'),
    (652, 'Electro Tune', 'Oil Change', 'Exterior and interior cleaning services'),
    (653, 'Sunshine Detailing', 'Regular Maintenance', 'Deep cleaning of the vehicle interior'),
    (654, 'Express Oil Change', 'Oil Change', 'Scheduled maintenance and inspection'),
    (655, 'Brake Master', 'Transmission Check', 'Replacement of worn-out brake components'),
    (656, 'Electro Tune', 'Brake Replacement', 'Deep cleaning of the vehicle interior'),
    (657, 'XYZ Repairs', 'Oil Change', 'Check and repair electrical components'),
    (658, 'Brake Master', 'Brake Inspection', 'Fast and efficient oil change service'),
    (659, 'XYZ Repairs', 'Brake Inspection', 'Deep cleaning of the vehicle interior'),
    (660, 'XYZ Repairs', 'Electrical System Check', 'Quick oil change with minimal waiting time'),
    (661, 'Sparkle Wash', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (662, 'Coolant Experts', 'Brake Inspection', 'Deep cleaning of the vehicle interior'),
    (663, 'Sunshine Detailing', 'Car Wash', 'Thorough inspection of transmission components'),
    (664, 'Sparkle Wash', 'Brake Inspection', 'Professional coolant system flushing'),
    (665, 'Brake Master', 'Coolant Flush', 'Replacement of worn-out brake components'),
    (666, 'Speedy Repairs', 'Brake Replacement', 'Deep cleaning of the vehicle interior'),
    (667, 'Brake Master', 'Brake Inspection', 'Scheduled maintenance and inspection'),
    (668, 'Sparkle Wash', 'Car Wash', 'Quick oil change with minimal waiting time'),
    (669, 'Sunshine Detailing', 'Express Oil Change', 'Fast and efficient oil change service'),
    (670, 'Sunshine Detailing', 'Car Wash', 'Deep cleaning of the vehicle interior'),
    (671, 'Brake Master', 'Transmission Check', 'Quick oil change with minimal waiting time'),
    (672, 'ABC Service Company', 'Brake Replacement', 'Fast and efficient oil change service'),
    (673, 'Express Oil Change', 'Interior Detailing', 'Check and repair electrical components'),
    (674, 'QuickOil', 'Regular Maintenance', 'Deep cleaning of the vehicle interior'),
    (675, 'QuickOil', 'Coolant Flush', 'Detailed inspection of brake system'),
    (676, 'Electro Tune', 'Brake Replacement', 'Fast and efficient oil change service'),
    (677, 'ABC Service Company', 'Transmission Check', 'Exterior and interior cleaning services'),
    (678, 'Express Oil Change', 'Interior Detailing', 'Professional coolant system flushing'),
    (679, 'Electro Tune', 'Electrical System Check', 'Fast and efficient oil change service'),
    (680, 'Electro Tune', 'Express Oil Change', 'Professional coolant system flushing'),
    (681, 'Electro Tune', 'Car Wash', 'Thorough inspection of transmission components'),
    (682, 'Brake Master', 'Car Wash', 'Detailed inspection of brake system'),
    (683, 'Electro Tune', 'Brake Inspection', 'Professional coolant system flushing'),
    (684, 'Coolant Experts', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (685, 'Electro Tune', 'Oil Change', 'Professional coolant system flushing'),
    (686, 'Electro Tune', 'Brake Replacement', 'Quick oil change with minimal waiting time'),
    (687, 'Sparkle Wash', 'Coolant Flush', 'Professional coolant system flushing'),
    (688, 'Speedy Repairs', 'Interior Detailing', 'Deep cleaning of the vehicle interior'),
    (689, 'Coolant Experts', 'Brake Replacement', 'Exterior and interior cleaning services'),
    (690, 'ABC Service Company', 'Transmission Check', 'Scheduled maintenance and inspection'),
    (691, 'QuickOil', 'Coolant Flush', 'Detailed inspection of brake system'),
    (692, 'ABC Service Company', 'Electrical System Check', 'Check and repair electrical components'),
    (693, 'QuickOil', 'Car Wash', 'Professional coolant system flushing'),
    (694, 'QuickOil', 'Brake Replacement', 'Exterior and interior cleaning services'),
    (695, 'Electro Tune', 'Coolant Flush', 'Detailed inspection of brake system'),
    (696, 'Brake Master', 'Interior Detailing', 'Detailed inspection of brake system'),
    (697, 'Electro Tune', 'Transmission Check', 'Thorough inspection of transmission components'),
    (698, 'XYZ Repairs', 'Brake Replacement', 'Thorough inspection of transmission components'),
    (699, 'Electro Tune', 'Express Oil Change', 'Professional coolant system flushing'),
    (700, 'Brake Master', 'Electrical System Check', 'Detailed inspection of brake system'),
    (701, 'Electro Tune', 'Brake Replacement', 'Detailed inspection of brake system'),
    (702, 'Coolant Experts', 'Coolant Flush', 'Exterior and interior cleaning services'),
    (703, 'ABC Service Company', 'Brake Inspection', 'Exterior and interior cleaning services'),
    (704, 'QuickOil', 'Interior Detailing', 'Check and repair electrical components'),
    (705, 'Sparkle Wash', 'Brake Replacement', 'Thorough inspection of transmission components'),
    (706, 'XYZ Repairs', 'Electrical System Check', 'Deep cleaning of the vehicle interior'),
    (707, 'Sparkle Wash', 'Interior Detailing', 'Deep cleaning of the vehicle interior'),
    (708, 'XYZ Repairs', 'Transmission Check', 'Replacement of worn-out brake components'),
    (709, 'XYZ Repairs', 'Transmission Check', 'Thorough inspection of transmission components'),
    (710, 'Speedy Repairs', 'Car Wash', 'Quick oil change with minimal waiting time'),
    (711, 'Brake Master', 'Oil Change', 'Replacement of worn-out brake components'),
    (712, 'XYZ Repairs', 'Interior Detailing', 'Thorough inspection of transmission components'),
    (713, 'Electro Tune', 'Brake Inspection', 'Fast and efficient oil change service'),
    (714, 'Speedy Repairs', 'Interior Detailing', 'Scheduled maintenance and inspection'),
    (715, 'XYZ Repairs', 'Brake Replacement', 'Detailed inspection of brake system'),
    (716, 'QuickOil', 'Car Wash', 'Scheduled maintenance and inspection'),
    (717, 'Electro Tune', 'Brake Replacement', 'Check and repair electrical components'),
    (718, 'XYZ Repairs', 'Brake Inspection', 'Quick oil change with minimal waiting time'),
    (719, 'Speedy Repairs', 'Brake Inspection', 'Fast and efficient oil change service'),
    (720, 'Speedy Repairs', 'Express Oil Change', 'Quick oil change with minimal waiting time'),
    (721, 'Sunshine Detailing', 'Oil Change', 'Exterior and interior cleaning services'),
    (722, 'Electro Tune', 'Regular Maintenance', 'Thorough inspection of transmission components'),
    (723, 'Brake Master', 'Regular Maintenance', 'Scheduled maintenance and inspection'),
    (724, 'Sparkle Wash', 'Oil Change', 'Check and repair electrical components'),
    (725, 'Sparkle Wash', 'Interior Detailing', 'Professional coolant system flushing'),
    (726, 'QuickOil', 'Electrical System Check', 'Fast and efficient oil change service'),
    (727, 'Speedy Repairs', 'Brake Replacement', 'Professional coolant system flushing'),
    (728, 'Coolant Experts', 'Brake Inspection', 'Deep cleaning of the vehicle interior'),
    (729, 'Coolant Experts', 'Express Oil Change', 'Detailed inspection of brake system'),
    (730, 'Electro Tune', 'Coolant Flush', 'Scheduled maintenance and inspection'),
    (731, 'QuickOil', 'Coolant Flush', 'Fast and efficient oil change service'),
    (732, 'Sparkle Wash', 'Brake Inspection', 'Deep cleaning of the vehicle interior'),
    (733, 'Sparkle Wash', 'Oil Change', 'Fast and efficient oil change service'),
    (734, 'Coolant Experts', 'Transmission Check', 'Detailed inspection of brake system'),
    (735, 'Brake Master', 'Transmission Check', 'Professional coolant system flushing'),
    (736, 'QuickOil', 'Coolant Flush', 'Exterior and interior cleaning services'),
    (737, 'Sunshine Detailing', 'Car Wash', 'Replacement of worn-out brake components'),
    (738, 'Speedy Repairs', 'Regular Maintenance', 'Check and repair electrical components'),
    (739, 'ABC Service Company', 'Brake Inspection', 'Check and repair electrical components'),
    (740, 'QuickOil', 'Brake Replacement', 'Deep cleaning of the vehicle interior'),
    (741, 'Express Oil Change', 'Car Wash', 'Detailed inspection of brake system'),
    (742, 'ABC Service Company', 'Car Wash', 'Fast and efficient oil change service'),
    (743, 'QuickOil', 'Coolant Flush', 'Detailed inspection of brake system'),
    (744, 'Speedy Repairs', 'Transmission Check', 'Scheduled maintenance and inspection'),
    (745, 'Sunshine Detailing', 'Transmission Check', 'Check and repair electrical components'),
    (746, 'Express Oil Change', 'Oil Change', 'Fast and efficient oil change service'),
    (747, 'Sparkle Wash', 'Electrical System Check', 'Fast and efficient oil change service'),
    (748, 'Sparkle Wash', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (749, 'Electro Tune', 'Express Oil Change', 'Scheduled maintenance and inspection'),
    (750, 'QuickOil', 'Oil Change', 'Deep cleaning of the vehicle interior'),
    (751, 'Speedy Repairs', 'Car Wash', 'Deep cleaning of the vehicle interior'),
    (752, 'Electro Tune', 'Brake Replacement', 'Check and repair electrical components'),
    (753, 'Speedy Repairs', 'Car Wash', 'Detailed inspection of brake system'),
    (754, 'Speedy Repairs', 'Coolant Flush', 'Fast and efficient oil change service'),
    (755, 'ABC Service Company', 'Express Oil Change', 'Professional coolant system flushing'),
    (756, 'XYZ Repairs', 'Express Oil Change', 'Check and repair electrical components'),
    (757, 'Brake Master', 'Brake Inspection', 'Professional coolant system flushing'),
    (758, 'Brake Master', 'Transmission Check', 'Detailed inspection of brake system'),
    (759, 'Sunshine Detailing', 'Car Wash', 'Scheduled maintenance and inspection'),
    (760, 'Electro Tune', 'Transmission Check', 'Replacement of worn-out brake components'),
    (761, 'Speedy Repairs', 'Transmission Check', 'Quick oil change with minimal waiting time'),
    (762, 'Coolant Experts', 'Coolant Flush', 'Detailed inspection of brake system'),
    (763, 'XYZ Repairs', 'Interior Detailing', 'Scheduled maintenance and inspection'),
    (764, 'Sunshine Detailing', 'Express Oil Change', 'Thorough inspection of transmission components'),
    (765, 'Coolant Experts', 'Transmission Check', 'Fast and efficient oil change service'),
    (766, 'Electro Tune', 'Express Oil Change', 'Scheduled maintenance and inspection'),
    (767, 'Brake Master', 'Brake Replacement', 'Fast and efficient oil change service'),
    (768, 'XYZ Repairs', 'Car Wash', 'Thorough inspection of transmission components'),
    (769, 'Sparkle Wash', 'Oil Change', 'Detailed inspection of brake system'),
    (770, 'XYZ Repairs', 'Coolant Flush', 'Thorough inspection of transmission components'),
    (771, 'Brake Master', 'Coolant Flush', 'Check and repair electrical components'),
    (772, 'QuickOil', 'Interior Detailing', 'Fast and efficient oil change service'),
    (773, 'Speedy Repairs', 'Electrical System Check', 'Professional coolant system flushing'),
    (774, 'Electro Tune', 'Express Oil Change', 'Professional coolant system flushing'),
    (775, 'Coolant Experts', 'Car Wash', 'Replacement of worn-out brake components'),
    (776, 'Coolant Experts', 'Electrical System Check', 'Thorough inspection of transmission components'),
    (777, 'ABC Service Company', 'Brake Replacement', 'Scheduled maintenance and inspection'),
    (778, 'Electro Tune', 'Brake Replacement', 'Fast and efficient oil change service'),
    (779, 'Coolant Experts', 'Brake Inspection', 'Deep cleaning of the vehicle interior'),
    (780, 'Speedy Repairs', 'Car Wash', 'Thorough inspection of transmission components'),
    (781, 'Speedy Repairs', 'Coolant Flush', 'Fast and efficient oil change service'),
    (782, 'Coolant Experts', 'Regular Maintenance', 'Thorough inspection of transmission components'),
    (783, 'ABC Service Company', 'Interior Detailing', 'Professional coolant system flushing'),
    (784, 'XYZ Repairs', 'Interior Detailing', 'Replacement of worn-out brake components'),
    (785, 'Speedy Repairs', 'Coolant Flush', 'Fast and efficient oil change service'),
    (786, 'Sunshine Detailing', 'Brake Replacement', 'Deep cleaning of the vehicle interior'),
    (787, 'Electro Tune', 'Brake Replacement', 'Deep cleaning of the vehicle interior'),
    (788, 'QuickOil', 'Express Oil Change', 'Exterior and interior cleaning services'),
    (789, 'Sparkle Wash', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (790, 'Brake Master', 'Oil Change', 'Deep cleaning of the vehicle interior'),
    (791, 'Coolant Experts', 'Transmission Check', 'Detailed inspection of brake system'),
    (792, 'Brake Master', 'Coolant Flush', 'Quick oil change with minimal waiting time'),
    (793, 'ABC Service Company', 'Oil Change', 'Thorough inspection of transmission components'),
    (794, 'QuickOil', 'Brake Inspection', 'Replacement of worn-out brake components'),
    (795, 'Electro Tune', 'Interior Detailing', 'Deep cleaning of the vehicle interior'),
    (796, 'Speedy Repairs', 'Regular Maintenance', 'Check and repair electrical components'),
    (797, 'QuickOil', 'Coolant Flush', 'Detailed inspection of brake system'),
    (798, 'Brake Master', 'Coolant Flush', 'Check and repair electrical components'),
    (799, 'XYZ Repairs', 'Coolant Flush', 'Deep cleaning of the vehicle interior'),
    (800, 'ABC Service Company', 'Express Oil Change', 'Fast and efficient oil change service'),
    (801, 'Electro Tune', 'Interior Detailing', 'Quick oil change with minimal waiting time'),
    (802, 'Electro Tune', 'Regular Maintenance', 'Check and repair electrical components'),
    (803, 'Express Oil Change', 'Oil Change', 'Replacement of worn-out brake components'),
    (804, 'Sparkle Wash', 'Oil Change', 'Check and repair electrical components'),
    (805, 'ABC Service Company', 'Transmission Check', 'Replacement of worn-out brake components'),
    (806, 'Speedy Repairs', 'Coolant Flush', 'Exterior and interior cleaning services'),
    (807, 'ABC Service Company', 'Brake Inspection', 'Thorough inspection of transmission components'),
    (808, 'Electro Tune', 'Electrical System Check', 'Exterior and interior cleaning services'),
    (809, 'Brake Master', 'Brake Inspection', 'Check and repair electrical components'),
    (810, 'Coolant Experts', 'Oil Change', 'Professional coolant system flushing'),
    (811, 'Brake Master', 'Regular Maintenance', 'Check and repair electrical components'),
    (812, 'Speedy Repairs', 'Car Wash', 'Exterior and interior cleaning services'),
    (813, 'Speedy Repairs', 'Oil Change', 'Thorough inspection of transmission components'),
    (814, 'Sparkle Wash', 'Coolant Flush', 'Replacement of worn-out brake components'),
    (815, 'ABC Service Company', 'Interior Detailing', 'Replacement of worn-out brake components'),
    (816, 'Sparkle Wash', 'Express Oil Change', 'Deep cleaning of the vehicle interior'),
    (817, 'Express Oil Change', 'Transmission Check', 'Exterior and interior cleaning services'),
    (818, 'Sparkle Wash', 'Regular Maintenance', 'Scheduled maintenance and inspection'),
    (819, 'QuickOil', 'Car Wash', 'Replacement of worn-out brake components'),
    (820, 'Coolant Experts', 'Express Oil Change', 'Check and repair electrical components'),
    (821, 'Brake Master', 'Express Oil Change', 'Professional coolant system flushing'),
    (822, 'Coolant Experts', 'Brake Inspection', 'Thorough inspection of transmission components'),
    (823, 'Sparkle Wash', 'Car Wash', 'Thorough inspection of transmission components'),
    (824, 'Speedy Repairs', 'Brake Inspection', 'Scheduled maintenance and inspection'),
    (825, 'Electro Tune', 'Regular Maintenance', 'Professional coolant system flushing'),
    (826, 'Speedy Repairs', 'Oil Change', 'Fast and efficient oil change service'),
    (827, 'Sunshine Detailing', 'Regular Maintenance', 'Scheduled maintenance and inspection'),
    (828, 'Coolant Experts', 'Regular Maintenance', 'Quick oil change with minimal waiting time'),
    (829, 'Coolant Experts', 'Interior Detailing', 'Scheduled maintenance and inspection'),
    (830, 'Coolant Experts', 'Brake Replacement', 'Deep cleaning of the vehicle interior'),
    (831, 'Express Oil Change', 'Brake Inspection', 'Exterior and interior cleaning services'),
    (832, 'Coolant Experts', 'Interior Detailing', 'Fast and efficient oil change service'),
    (833, 'Sunshine Detailing', 'Car Wash', 'Check and repair electrical components'),
    (834, 'Express Oil Change', 'Oil Change', 'Replacement of worn-out brake components'),
    (835, 'Speedy Repairs', 'Coolant Flush', 'Professional coolant system flushing'),
    (836, 'Sunshine Detailing', 'Regular Maintenance', 'Replacement of worn-out brake components'),
    (837, 'Coolant Experts', 'Car Wash', 'Check and repair electrical components'),
    (838, 'Express Oil Change', 'Regular Maintenance', 'Deep cleaning of the vehicle interior'),
    (839, 'Express Oil Change', 'Express Oil Change', 'Detailed inspection of brake system'),
    (840, 'Brake Master', 'Express Oil Change', 'Quick oil change with minimal waiting time'),
    (841, 'ABC Service Company', 'Brake Replacement', 'Scheduled maintenance and inspection'),
    (842, 'Coolant Experts', 'Coolant Flush', 'Check and repair electrical components'),
    (843, 'Speedy Repairs', 'Car Wash', 'Quick oil change with minimal waiting time'),
    (844, 'Speedy Repairs', 'Coolant Flush', 'Thorough inspection of transmission components'),
    (845, 'Brake Master', 'Oil Change', 'Exterior and interior cleaning services'),
    (846, 'XYZ Repairs', 'Coolant Flush', 'Check and repair electrical components'),
    (847, 'QuickOil', 'Oil Change', 'Check and repair electrical components'),
    (848, 'Sparkle Wash', 'Transmission Check', 'Quick oil change with minimal waiting time'),
    (849, 'Speedy Repairs', 'Brake Inspection', 'Replacement of worn-out brake components'),
    (850, 'Electro Tune', 'Transmission Check', 'Detailed inspection of brake system'),
    (851, 'Sunshine Detailing', 'Coolant Flush', 'Fast and efficient oil change service'),
    (852, 'Speedy Repairs', 'Coolant Flush', 'Replacement of worn-out brake components'),
    (853, 'Speedy Repairs', 'Oil Change', 'Check and repair electrical components'),
    (854, 'QuickOil', 'Transmission Check', 'Check and repair electrical components'),
    (855, 'Electro Tune', 'Transmission Check', 'Check and repair electrical components'),
    (856, 'Sunshine Detailing', 'Oil Change', 'Exterior and interior cleaning services'),
    (857, 'Brake Master', 'Oil Change', 'Check and repair electrical components'),
    (858, 'ABC Service Company', 'Express Oil Change', 'Deep cleaning of the vehicle interior'),
    (859, 'Coolant Experts', 'Brake Replacement', 'Replacement of worn-out brake components'),
    (860, 'Brake Master', 'Oil Change', 'Deep cleaning of the vehicle interior'),
    (861, 'ABC Service Company', 'Regular Maintenance', 'Scheduled maintenance and inspection'),
    (862, 'Electro Tune', 'Oil Change', 'Thorough inspection of transmission components'),
    (863, 'Electro Tune', 'Brake Replacement', 'Fast and efficient oil change service'),
    (864, 'Electro Tune', 'Transmission Check', 'Thorough inspection of transmission components'),
    (865, 'ABC Service Company', 'Interior Detailing', 'Scheduled maintenance and inspection'),
    (866, 'Express Oil Change', 'Oil Change', 'Deep cleaning of the vehicle interior'),
    (867, 'XYZ Repairs', 'Transmission Check', 'Quick oil change with minimal waiting time'),
    (868, 'Sunshine Detailing', 'Electrical System Check', 'Professional coolant system flushing'),
    (869, 'Sparkle Wash', 'Brake Replacement', 'Thorough inspection of transmission components'),
    (870, 'Sunshine Detailing', 'Transmission Check', 'Replacement of worn-out brake components'),
    (871, 'Brake Master', 'Brake Inspection', 'Quick oil change with minimal waiting time'),
    (872, 'ABC Service Company', 'Transmission Check', 'Check and repair electrical components'),
    (873, 'Brake Master', 'Transmission Check', 'Thorough inspection of transmission components'),
    (874, 'Coolant Experts', 'Transmission Check', 'Detailed inspection of brake system'),
    (875, 'Sparkle Wash', 'Oil Change', 'Detailed inspection of brake system'),
    (876, 'Sparkle Wash', 'Car Wash', 'Check and repair electrical components'),
    (877, 'QuickOil', 'Brake Replacement', 'Thorough inspection of transmission components'),
    (878, 'Sparkle Wash', 'Oil Change', 'Quick oil change with minimal waiting time'),
    (879, 'Express Oil Change', 'Transmission Check', 'Scheduled maintenance and inspection'),
    (880, 'Coolant Experts', 'Oil Change', 'Replacement of worn-out brake components'),
    (881, 'Electro Tune', 'Interior Detailing', 'Scheduled maintenance and inspection'),
    (882, 'Sunshine Detailing', 'Interior Detailing', 'Quick oil change with minimal waiting time'),
    (883, 'Sunshine Detailing', 'Transmission Check', 'Exterior and interior cleaning services'),
    (884, 'Sparkle Wash', 'Express Oil Change', 'Replacement of worn-out brake components'),
    (885, 'Electro Tune', 'Interior Detailing', 'Deep cleaning of the vehicle interior'),
    (886, 'ABC Service Company', 'Regular Maintenance', 'Thorough inspection of transmission components'),
    (887, 'ABC Service Company', 'Express Oil Change', 'Replacement of worn-out brake components'),
    (888, 'Sunshine Detailing', 'Express Oil Change', 'Fast and efficient oil change service'),
    (889, 'Sunshine Detailing', 'Regular Maintenance', 'Quick oil change with minimal waiting time'),
    (890, 'Express Oil Change', 'Brake Replacement', 'Detailed inspection of brake system'),
    (891, 'Speedy Repairs', 'Electrical System Check', 'Thorough inspection of transmission components'),
    (892, 'Sparkle Wash', 'Interior Detailing', 'Exterior and interior cleaning services'),
    (893, 'XYZ Repairs', 'Regular Maintenance', 'Quick oil change with minimal waiting time'),
    (894, 'QuickOil', 'Car Wash', 'Professional coolant system flushing'),
    (895, 'Coolant Experts', 'Car Wash', 'Thorough inspection of transmission components'),
    (896, 'ABC Service Company', 'Brake Inspection', 'Exterior and interior cleaning services'),
    (897, 'XYZ Repairs', 'Brake Replacement', 'Thorough inspection of transmission components'),
    (898, 'XYZ Repairs', 'Express Oil Change', 'Detailed inspection of brake system'),
    (899, 'Sparkle Wash', 'Transmission Check', 'Professional coolant system flushing'),
    (900, 'Sparkle Wash', 'Brake Inspection', 'Fast and efficient oil change service'),
    (901, 'XYZ Repairs', 'Regular Maintenance', 'Professional coolant system flushing'),
    (902, 'Electro Tune', 'Interior Detailing', 'Check and repair electrical components'),
    (903, 'QuickOil', 'Express Oil Change', 'Thorough inspection of transmission components'),
    (904, 'Electro Tune', 'Express Oil Change', 'Quick oil change with minimal waiting time'),
    (905, 'Express Oil Change', 'Express Oil Change', 'Fast and efficient oil change service'),
    (906, 'Express Oil Change', 'Transmission Check', 'Scheduled maintenance and inspection'),
    (907, 'XYZ Repairs', 'Brake Replacement', 'Detailed inspection of brake system'),
    (908, 'Sparkle Wash', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (909, 'Coolant Experts', 'Oil Change', 'Replacement of worn-out brake components'),
    (910, 'Express Oil Change', 'Car Wash', 'Thorough inspection of transmission components'),
    (911, 'Electro Tune', 'Car Wash', 'Fast and efficient oil change service'),
    (912, 'Express Oil Change', 'Brake Inspection', 'Scheduled maintenance and inspection'),
    (913, 'Sunshine Detailing', 'Coolant Flush', 'Quick oil change with minimal waiting time'),
    (914, 'XYZ Repairs', 'Regular Maintenance', 'Check and repair electrical components'),
    (915, 'XYZ Repairs', 'Brake Replacement', 'Scheduled maintenance and inspection'),
    (916, 'Express Oil Change', 'Oil Change', 'Scheduled maintenance and inspection'),
    (917, 'Brake Master', 'Car Wash', 'Check and repair electrical components'),
    (918, 'Electro Tune', 'Interior Detailing', 'Deep cleaning of the vehicle interior'),
    (919, 'Brake Master', 'Brake Replacement', 'Fast and efficient oil change service'),
    (920, 'QuickOil', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (921, 'ABC Service Company', 'Electrical System Check', 'Detailed inspection of brake system'),
    (922, 'Brake Master', 'Brake Inspection', 'Thorough inspection of transmission components'),
    (923, 'ABC Service Company', 'Interior Detailing', 'Scheduled maintenance and inspection'),
    (924, 'Sparkle Wash', 'Brake Replacement', 'Fast and efficient oil change service'),
    (925, 'Coolant Experts', 'Brake Replacement', 'Thorough inspection of transmission components'),
    (926, 'Speedy Repairs', 'Interior Detailing', 'Thorough inspection of transmission components'),
    (927, 'XYZ Repairs', 'Coolant Flush', 'Exterior and interior cleaning services'),
    (928, 'ABC Service Company', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (929, 'Express Oil Change', 'Brake Replacement', 'Quick oil change with minimal waiting time'),
    (930, 'QuickOil', 'Transmission Check', 'Replacement of worn-out brake components'),
    (931, 'Sparkle Wash', 'Oil Change', 'Scheduled maintenance and inspection'),
    (932, 'Electro Tune', 'Car Wash', 'Quick oil change with minimal waiting time'),
    (933, 'Coolant Experts', 'Coolant Flush', 'Check and repair electrical components'),
    (934, 'QuickOil', 'Transmission Check', 'Fast and efficient oil change service'),
    (935, 'Sparkle Wash', 'Oil Change', 'Deep cleaning of the vehicle interior'),
    (936, 'XYZ Repairs', 'Regular Maintenance', 'Replacement of worn-out brake components'),
    (937, 'Express Oil Change', 'Regular Maintenance', 'Professional coolant system flushing'),
    (938, 'XYZ Repairs', 'Electrical System Check', 'Professional coolant system flushing'),
    (939, 'XYZ Repairs', 'Car Wash', 'Professional coolant system flushing'),
    (940, 'Brake Master', 'Coolant Flush', 'Scheduled maintenance and inspection'),
    (941, 'Sparkle Wash', 'Brake Replacement', 'Exterior and interior cleaning services'),
    (942, 'QuickOil', 'Electrical System Check', 'Quick oil change with minimal waiting time'),
    (943, 'Sunshine Detailing', 'Brake Inspection', 'Check and repair electrical components'),
    (944, 'ABC Service Company', 'Transmission Check', 'Check and repair electrical components'),
    (945, 'Brake Master', 'Express Oil Change', 'Professional coolant system flushing'),
    (946, 'Coolant Experts', 'Brake Replacement', 'Quick oil change with minimal waiting time'),
    (947, 'Express Oil Change', 'Brake Replacement', 'Check and repair electrical components'),
    (948, 'Coolant Experts', 'Express Oil Change', 'Deep cleaning of the vehicle interior'),
    (949, 'Sunshine Detailing', 'Brake Replacement', 'Professional coolant system flushing'),
    (950, 'ABC Service Company', 'Transmission Check', 'Exterior and interior cleaning services'),
    (951, 'Sparkle Wash', 'Brake Inspection', 'Professional coolant system flushing'),
    (952, 'Speedy Repairs', 'Express Oil Change', 'Replacement of worn-out brake components'),
    (953, 'Coolant Experts', 'Regular Maintenance', 'Check and repair electrical components'),
    (954, 'Coolant Experts', 'Interior Detailing', 'Thorough inspection of transmission components'),
    (955, 'Speedy Repairs', 'Brake Replacement', 'Deep cleaning of the vehicle interior'),
    (956, 'QuickOil', 'Interior Detailing', 'Deep cleaning of the vehicle interior'),
    (957, 'XYZ Repairs', 'Oil Change', 'Quick oil change with minimal waiting time'),
    (958, 'Express Oil Change', 'Interior Detailing', 'Exterior and interior cleaning services'),
    (959, 'ABC Service Company', 'Express Oil Change', 'Fast and efficient oil change service'),
    (960, 'Speedy Repairs', 'Electrical System Check', 'Detailed inspection of brake system'),
    (961, 'ABC Service Company', 'Car Wash', 'Deep cleaning of the vehicle interior'),
    (962, 'ABC Service Company', 'Electrical System Check', 'Scheduled maintenance and inspection'),
    (963, 'QuickOil', 'Transmission Check', 'Thorough inspection of transmission components'),
    (964, 'XYZ Repairs', 'Oil Change', 'Thorough inspection of transmission components'),
    (965, 'ABC Service Company', 'Transmission Check', 'Check and repair electrical components'),
    (966, 'Speedy Repairs', 'Express Oil Change', 'Replacement of worn-out brake components'),
    (967, 'Speedy Repairs', 'Electrical System Check', 'Exterior and interior cleaning services'),
    (968, 'ABC Service Company', 'Electrical System Check', 'Detailed inspection of brake system'),
    (969, 'Brake Master', 'Interior Detailing', 'Check and repair electrical components'),
    (970, 'ABC Service Company', 'Car Wash', 'Detailed inspection of brake system'),
    (971, 'Electro Tune', 'Brake Inspection', 'Replacement of worn-out brake components'),
    (972, 'Brake Master', 'Transmission Check', 'Replacement of worn-out brake components'),
    (973, 'XYZ Repairs', 'Car Wash', 'Replacement of worn-out brake components'),
    (974, 'XYZ Repairs', 'Regular Maintenance', 'Deep cleaning of the vehicle interior'),
    (975, 'Express Oil Change', 'Express Oil Change', 'Professional coolant system flushing'),
    (976, 'Electro Tune', 'Transmission Check', 'Quick oil change with minimal waiting time'),
    (977, 'Electro Tune', 'Car Wash', 'Fast and efficient oil change service'),
    (978, 'QuickOil', 'Brake Replacement', 'Quick oil change with minimal waiting time'),
    (979, 'Sparkle Wash', 'Car Wash', 'Detailed inspection of brake system'),
    (980, 'Sunshine Detailing', 'Regular Maintenance', 'Check and repair electrical components'),
    (981, 'XYZ Repairs', 'Brake Inspection', 'Deep cleaning of the vehicle interior'),
    (982, 'Express Oil Change', 'Regular Maintenance', 'Thorough inspection of transmission components'),
    (983, 'Express Oil Change', 'Coolant Flush', 'Scheduled maintenance and inspection'),
    (984, 'ABC Service Company', 'Brake Replacement', 'Fast and efficient oil change service'),
    (985, 'Electro Tune', 'Interior Detailing', 'Thorough inspection of transmission components'),
    (986, 'XYZ Repairs', 'Regular Maintenance', 'Replacement of worn-out brake components'),
    (987, 'XYZ Repairs', 'Brake Replacement', 'Professional coolant system flushing'),
    (988, 'Sparkle Wash', 'Coolant Flush', 'Fast and efficient oil change service'),
    (989, 'Sunshine Detailing', 'Coolant Flush', 'Scheduled maintenance and inspection'),
    (990, 'QuickOil', 'Express Oil Change', 'Fast and efficient oil change service'),
    (991, 'XYZ Repairs', 'Express Oil Change', 'Exterior and interior cleaning services'),
    (992, 'Electro Tune', 'Brake Replacement', 'Quick oil change with minimal waiting time'),
    (993, 'QuickOil', 'Coolant Flush', 'Thorough inspection of transmission components'),
    (994, 'Electro Tune', 'Brake Replacement', 'Fast and efficient oil change service'),
    (995, 'Speedy Repairs', 'Interior Detailing', 'Check and repair electrical components'),
    (996, 'Brake Master', 'Express Oil Change', 'Fast and efficient oil change service'),
    (997, 'Coolant Experts', 'Regular Maintenance', 'Detailed inspection of brake system'),
    (998, 'Sparkle Wash', 'Transmission Check', 'Fast and efficient oil change service'),
    (999, 'QuickOil', 'Interior Detailing', 'Exterior and interior cleaning services'),
    (1000, 'Express Oil Change', 'Oil Change', 'Replacement of worn-out brake components');