INSERT INTO Vehicle (VehicleId, VehicleType, ServiceInfo, InsuranceInfo)
VALUES
    (1, 'Electric Car', 'Family-friendly model', 'YES'),
    (2, 'Hatchback', 'Fuel-efficient model', 'NO'),
    (3, 'Compact', 'Luxury vehicle maintenance', 'YES'),
    (4, 'Electric Car', 'Specialized care', 'NO'),
    (5, 'Hatchback', 'Heavy-duty maintenance', 'YES'),
    (6, 'Convertible', 'Family-friendly model', 'NO'),
    (7, 'Truck', 'Regularly serviced', 'YES'),
    (8, 'Limousine', 'Regularly serviced', 'NO'),
    (9, 'Convertible', 'Fuel-efficient model', 'YES'),
    (10, 'Motorcycle', 'Fuel-efficient model', 'NO'),
    (11, 'Compact', 'Heavy-duty maintenance', 'YES'),
    (12, 'Limousine', 'Heavy-duty maintenance', 'NO'),
    (13, 'Electric Car', 'Luxury vehicle maintenance', 'YES'),
    (14, 'Sedan', 'Monthly check-ups', 'NO'),
    (15, 'Hatchback', 'Heavy-duty maintenance', 'YES'),
    (16, 'Compact', 'Heavy-duty maintenance', 'NO'),
    (17, 'Limousine', 'Battery system inspection', 'YES'),
    (18, 'Hatchback', 'Specialized care', 'NO'),
    (19, 'Truck', 'Battery system inspection', 'YES'),
    (20, 'Compact', 'Specialized care', 'NO'),
    (21, 'Motorcycle', 'Specialized care', 'YES'),
    (22, 'Limousine', 'Specialized care', 'NO'),
    (23, 'Truck', 'Fuel-efficient model', 'YES'),
    (24, 'Limousine', 'Bi-annual check-ups', 'NO'),
    (25, 'Limousine', 'Bi-annual check-ups', 'YES'),
    (26, 'Motorcycle', 'Specialized care', 'NO'),
    (27, 'Hatchback', 'Family-friendly model', 'YES'),
    (28, 'Minivan', 'Bi-annual check-ups', 'NO'),
    (29, 'Convertible', 'Battery system inspection', 'YES'),
    (30, 'Electric Car', 'Family-friendly model', 'NO'),
    (31, 'Sedan', 'Battery system inspection', 'YES'),
    (32, 'SUV', 'Heavy-duty maintenance', 'NO'),
    (33, 'SUV', 'Luxury vehicle maintenance', 'YES'),
    (34, 'Compact', 'Heavy-duty maintenance', 'NO'),
    (35, 'Minivan', 'Specialized care', 'YES'),
    (36, 'Convertible', 'Monthly check-ups', 'NO'),
    (37, 'Sedan', 'Specialized care', 'YES'),
    (38, 'Convertible', 'Regularly serviced', 'NO'),
    (39, 'Limousine', 'Regularly serviced', 'YES'),
    (40, 'SUV', 'Heavy-duty maintenance', 'NO'),
    (41, 'Convertible', 'Luxury vehicle maintenance', 'YES'),
    (42, 'Motorcycle', 'Regularly serviced', 'NO'),
    (43, 'Minivan', 'Specialized care', 'YES'),
    (44, 'Sedan', 'Specialized care', 'NO'),
    (45, 'Electric Car', 'Bi-annual check-ups', 'YES'),
    (46, 'Hatchback', 'Heavy-duty maintenance', 'NO'),
    (47, 'Convertible', 'Bi-annual check-ups', 'YES'),
    (48, 'Minivan', 'Specialized care', 'NO'),
    (49, 'Sedan', 'Bi-annual check-ups', 'YES'),
    (50, 'Convertible', 'Heavy-duty maintenance', 'NO'),
    (51, 'SUV', 'Battery system inspection', 'YES'),
    (52, 'Limousine', 'Battery system inspection', 'NO'),
    (53, 'Motorcycle', 'Fuel-efficient model', 'YES'),
    (54, 'Limousine', 'Regularly serviced', 'NO'),
    (55, 'Limousine', 'Monthly check-ups', 'YES'),
    (56, 'Sedan', 'Battery system inspection', 'NO'),
    (57, 'Sedan', 'Battery system inspection', 'YES'),
    (58, 'SUV', 'Luxury vehicle maintenance', 'NO'),
    (59, 'Motorcycle', 'Monthly check-ups', 'YES'),
    (60, 'Truck', 'Monthly check-ups', 'NO'),
    (61, 'Motorcycle', 'Bi-annual check-ups', 'YES'),
    (62, 'Hatchback', 'Specialized care', 'NO'),
    (63, 'Truck', 'Specialized care', 'YES'),
    (64, 'Hatchback', 'Bi-annual check-ups', 'NO'),
    (65, 'Truck', 'Family-friendly model', 'YES'),
    (66, 'Limousine', 'Battery system inspection', 'NO'),
    (67, 'Minivan', 'Luxury vehicle maintenance', 'YES'),
    (68, 'SUV', 'Monthly check-ups', 'NO'),
    (69, 'Motorcycle', 'Specialized care', 'YES'),
    (70, 'Hatchback', 'Regularly serviced', 'NO'),
    (71, 'SUV', 'Monthly check-ups', 'YES'),
    (72, 'Motorcycle', 'Luxury vehicle maintenance', 'NO'),
    (73, 'Sedan', 'Regularly serviced', 'YES'),
    (74, 'Electric Car', 'Fuel-efficient model', 'NO'),
    (75, 'Truck', 'Specialized care', 'YES'),
    (76, 'Limousine', 'Luxury vehicle maintenance', 'NO'),
    (77, 'Truck', 'Luxury vehicle maintenance', 'YES'),
    (78, 'Compact', 'Specialized care', 'NO'),
    (79, 'Sedan', 'Battery system inspection', 'YES'),
    (80, 'Minivan', 'Specialized care', 'NO'),
    (81, 'SUV', 'Luxury vehicle maintenance', 'YES'),
    (82, 'Electric Car', 'Specialized care', 'NO'),
    (83, 'Truck', 'Regularly serviced', 'YES'),
    (84, 'SUV', 'Luxury vehicle maintenance', 'NO'),
    (85, 'Limousine', 'Specialized care', 'YES'),
    (86, 'Electric Car', 'Battery system inspection', 'NO'),
    (87, 'Minivan', 'Fuel-efficient model', 'YES'),
    (88, 'Limousine', 'Specialized care', 'NO'),
    (89, 'Hatchback', 'Bi-annual check-ups', 'YES'),
    (90, 'Minivan', 'Specialized care', 'NO'),
    (91, 'Hatchback', 'Regularly serviced', 'YES'),
    (92, 'SUV', 'Bi-annual check-ups', 'NO'),
    (93, 'Truck', 'Specialized care', 'YES'),
    (94, 'Truck', 'Heavy-duty maintenance', 'NO'),
    (95, 'Minivan', 'Family-friendly model', 'YES'),
    (96, 'Sedan', 'Specialized care', 'NO'),
    (97, 'Limousine', 'Specialized care', 'YES'),
    (98, 'Motorcycle', 'Battery system inspection', 'NO'),
    (99, 'SUV', 'Regularly serviced', 'YES'),
    (100, 'Compact', 'Monthly check-ups', 'NO');
